cypress-io/cypress-docker-images

README.md, browsers/chrome/Dockerfile, browsers/chrome/chrome.sh
Removes extra alias `/usr/bin/chrome`. User `node` is default and Chrome connects if running with `--no-sandbox`
=> remove extra user from chrome image, close #24

README.md
It looks like there was an extra `a` in `Check out our docs for a examples.`
I am hoping my next pull request for you will be a bit more technical! 😄
=> Fix small typo in README.md file

base/10/Dockerfile, base/8/Dockerfile
Upgrade to latest npm.
I'm able to use npm 5.6.0 or 6.1.0, but not any versions in between due to https://github.com/npm/npm/issues/19989. Seems good to upgrade to the latest anyway!
=> Upgrade npm to 6.1.0 (base/8 and base/10)

README.md, base/10/Dockerfile, base/6/Dockerfile, base/8/Dockerfile, base/README.md, browsers/README.md, browsers/chrome71/Dockerfile, browsers/chrome71/README.md, browsers/chrome71/build.sh
This PR includes the following:
- Added Chrome 71 browser image
- Updated base images for current LTS version (6, 8, and 10). 
- Made listing of tool versions in the container a little cleaner...like so:
```
node version:           v10.15.0
npm version:            6.6.0
yarn version:           1.12.3
debian version:         9.6
```
=> Node LTS updates and chrome71

README.md, browsers/README.md, browsers/node8.15.1-chrome73/Dockerfile, browsers/node8.15.1-chrome73/README.md, browsers/node8.15.1-chrome73/build.sh
- closes #90 
- closes #81 
Docker image tag `cypress/browsers:node8.15.1-chrome73`
```
node version:    v8.15.1 
yarn verison:    1.15.2 
debian version:  9.8 
Chrome version:  Google Chrome 73.0.3683.86  
git version:     git version 2.11.0
```
=> add Node 8.15.1 plus Chrome 73 image

README.md, base/10.15.3/Dockerfile, base/10.15.3/README.md, base/10.15.3/build.sh, base/README.md
- closes #94 
Docker tag `cypress/base:10.15.3`
```
node version:    v10.15.3 
yarn verison:    1.15.2 
debian version:  9.8
```
=> add Node 10.15.3 image

base/8.2.1/Dockerfile, base/8.2.1/README.md, base/8.2.1/build.sh, base/README.md, browsers/README.md, browsers/node8.2.1-chrome73/Dockerfile, browsers/node8.2.1-chrome73/README.md, browsers/node8.2.1-chrome73/build.sh
- closes #96 
Adding `cypress/base:8.2.1` image for testing Cypress 3.2.x
```
node version:    v8.2.1 
npm version:     5.3.0 
yarn verison:    1.12.3 
debian version:  8.11
```
Adding `cypress/browsers:node8.2.1-chrome73` image built on top of `cypress/base:8.2.1`
```
node version:    v8.2.1 
npm version:     5.3.0 
yarn verison:    1.12.3 
debian version:  8.11 
Chrome version:  Google Chrome 73.0.3683.86  
git version:     git version 2.1.4
```
=> add cypress/base:8.2.1 docker image

README.md, base/11.13.0/Dockerfile, base/11.13.0/README.md, base/11.13.0/build.sh, base/README.md, browsers/node11.13.0-chrome73/Dockerfile, browsers/node11.13.0-chrome73/README.md, browsers/node11.13.0-chrome73/build.sh
- temp image for people who need Node 11
- checking reduced size flags when building Docker image
```
node version:    v11.13.0 
yarn verison:    1.15.2 
debian version:  9.8
```
- built `cypress/browsers:node11.13.0-chrome73` on top of that
```
node version:    v11.13.0 
yarn verison:    1.15.2 
debian version:  9.8 
Chrome version:  Google Chrome 73.0.3683.103  
git version:     git version 2.11.0
```
- closes #86
=> Add base 11.13.0 image and with Chrome 73

included/Dockerfile, included/README.md, included/build.sh, included/test.sh
- full image with Cypress pre-installed, based on `cypress/base:12.1.0`
```
3.2.0: digest: sha256:9c7aab130b0e681bda3ac94c437af47d844e9dbfda377de7ff32640b4364d17f size: 3057
```
=> add cypress/included:3.2.0 image

base/8.16.0/Dockerfile, base/8.16.0/README.md, base/8.16.0/build.sh, base/README.md
- closes #109
```
node version:    v8.16.0 
yarn version:    1.16.0 
debian version:  9.9 
```
```
8.16.0: digest: sha256:a23ec1a30c3335a80ed2eb177ab9f03dce42ffd9a3968bf9628c14358c1c11a8 size: 2854
```
=> add cypress/base:8.16.0 image with Chinese fonts

included/3.2.0/test.sh, included/3.3.0/Dockerfile, included/3.3.0/README.md, included/3.3.0/build.sh, included/README.md
- closes #115 
```
node version:    v12.1.0 
yarn version:    1.15.2 
debian version:  9.8 
3.3.0: digest: sha256:ab3ec8dd2746723861bddfb76c58a9931c85df1a5080b5f8d1634d9516d1fa5e size: 3058
```
=> build cypress/included 3.3.0 image

base/README.md, base/centos7-12.4.0/Dockerfile, base/centos7-12.4.0/README.md, base/centos7-12.4.0/build.sh, test/Dockerfile
Add image `cypress/base:centos7-12.4.0`
```
node version:    v12.4.0
npm version:     6.9.0
yarn version:    1.16.0
centOS version:  CentOS Linux release 7.6.1810 (Core) 
```
=> add latest centos7 based on Node 12.4.0

included/3.3.2/Dockerfile, included/3.3.2/README.md, included/3.3.2/build.sh, test/Dockerfile
This PR adds the included image for cypress 3.3.2
Temporarily available on dockerhub as: tdamsma/included:3.3.2
=> Add included:3.3.2

base/12.0.0/Dockerfile, base/12.0.0/README.md, base/12.0.0/build.sh, base/README.md, browsers/README.md, browsers/node12.0.0-chrome75/Dockerfile, browsers/node12.0.0-chrome75/README.md, browsers/node12.0.0-chrome75/build.sh, test/Dockerfile
Add 2 new docker images to match the Node version for Electron 5.x:
* cypress/base:12.0.0
* cypress/browsers:12.0.0-chrome74
=> Add cypress/base:12.0.0, cypress/browsers:12.0.0-chrome75

browsers/README.md, browsers/node12.6.0-chrome75/Dockerfile, browsers/node12.6.0-chrome75/README.md, browsers/node12.6.0-chrome75/build.sh, included/3.4.0/Dockerfile, included/3.4.0/README.md, included/3.4.0/build.sh, included/README.md, test/Dockerfile
added `cypress/browsers:node12.6.0-chrome75` image
```
node version:    v12.6.0 
npm version:     6.10.0 
yarn version:    1.16.0 
debian version:  9.9 
Chrome version:  Google Chrome 75.0.3770.100  
git version:     git version 2.11.0
```
added `cypress/included:3.4.0` built on top of `cypress/browsers:node12.6.0-chrome75`
```
node version:    v12.6.0 
npm version:     6.10.0 
yarn version:    1.16.0 
debian version:  9.9 
```
- closes #128
=> added cypress/browsers:node12.6.0-chrome75 

browsers/README.md, browsers/node10.16.0-chrome76/Dockerfile, browsers/node10.16.0-chrome76/README.md, browsers/node10.16.0-chrome76/build.sh
Adds a new docker file to utilize node version 10.16.0 for Chrome browsers.
=> Add cypress/browsers:node10.16.0-chrome76

browsers/README.md, browsers/node8.9.3-npm6.10.1-chrome76-ff68/Dockerfile, browsers/node8.9.3-npm6.10.1-chrome76-ff68/README.md, browsers/node8.9.3-npm6.10.1-chrome76-ff68/build.sh
Pushed `cypress/browsers:node8.9.3-npm6.10.1-chrome76-ff68`
```
node version:    v8.9.3 
npm version:     6.10.1 
yarn version:    1.17.3 
debian version:  8.10 
Chrome version:  Google Chrome 76.0.3809.132  
Firefox version: Mozilla Firefox 68.0.2 
git version:     git version 2.1.4
```
=> add cypress/browsers:node8.9.3-npm6.10.1-chrome76-ff-68

browsers/README.md, browsers/node10.16.0-chrome77/Dockerfile, browsers/node10.16.0-chrome77/README.md, browsers/node10.16.0-chrome77/build.sh
I've built and tested this docker image containing Chrome 77.0.3865.90 and Node 10.16.0.
The image is not pushed to the Docker hub yet. Do we need the reviewers to approve this PR before pushing?
=> Node10.16.0 chrome77

browsers/README.md, browsers/node12.6.0-chrome77/Dockerfile, browsers/node12.6.0-chrome77/README.md, browsers/node12.6.0-chrome77/build.sh
I've built and tested this docker image containing Chrome 77.0.3865.90 and Node 12.6.0.
The image is not pushed to the Docker hub yet. Do we need the reviewers to approve this PR before pushing?
=> Docker image with Chrome 77 and Node 12.6.0

browsers/README.md, browsers/node12.0.0-chrome73/Dockerfile, browsers/node12.0.0-chrome73/README.md, browsers/node12.0.0-chrome73/build.sh
Matching version for Electron 5.0.10 (https://github.com/cypress-io/cypress/pull/4720)
=> Add cypress/browsers:node12.0.0-chrome73

base/README.md, browsers/README.md, included/README.md
This provides a convenient link to the Docker Hub page for each image variant and displays the docker pull count.
=> Add DockerHub badges

browsers/README.md, browsers/node12.13.0-chrome78-ff70/Dockerfile, browsers/node12.13.0-chrome78-ff70/README.md, browsers/node12.13.0-chrome78-ff70/build.sh, test/Dockerfile
Adding image `browsers/node12.13.0-chrome78-ff70/` with
```
node version:    v12.13.0 
npm version:     6.13.0 
yarn version:    1.19.1 
debian version:  9.11 
Chrome version:  Google Chrome 78.0.3904.97  
Firefox version: Mozilla Firefox 70.0.1 
git version:     git version 2.11.0
```
=> Add browser image with node 12.13.0 with chrome 78 and ff 70

browsers/README.md, browsers/node12.13.0-chrome78-ff70-brave78/Dockerfile, browsers/node12.13.0-chrome78-ff70-brave78/README.md, browsers/node12.13.0-chrome78-ff70-brave78/build.sh
Example building image with all browsers: Chrome, Firefox and Brave
```
node version:    v12.13.0 
npm version:     6.13.0 
yarn version:    1.19.1 
debian version:  9.11 
git version:     git version 2.11.0 
Chrome version:  Google Chrome 78.0.3904.97  
Firefox version: Mozilla Firefox 70.0.1 
Brave version:   Brave Browser 78.1.0.0
```
=> built Docker image with Brave browser v78

browsers/README.md, browsers/node12.8.1-chrome78-ff70/Dockerfile, browsers/node12.8.1-chrome78-ff70/README.md, browsers/node12.8.1-chrome78-ff70/build.sh
For the Electron 7.x upgrade.
```
node version:    v12.8.1 
npm version:     6.10.3 
yarn version:    1.17.3 
debian version:  9.11 
Chrome version:  Google Chrome 78.0.3904.97  
Firefox version: Mozilla Firefox 70.0.1 
git version:     git version 2.11.0 
```
=> Add node12.8.1-chrome78-ff70

browsers/node10.16.0-chrome77-ff71/Dockerfile, browsers/node12.8.1-chrome78-ff70/Dockerfile
add video codecs to existing firefox images that are missing them.
Couldn't add codecs to `browsers/node12.13.0-chrome78-ff70` since that image builds chrome, which needs to remain cached from my understanding
=> add video codecs to firefox images

included/3.8.1/Dockerfile, included/3.8.1/README.md, included/README.md
to allow running as non-root user right away. Related https://github.com/cypress-io/cypress-docker-images/pull/191
=> set permissions for image 3.8.1

README.md, examples/included-as-non-root-alternative/Dockerfile, examples/included-as-non-root-alternative/README.md, examples/included-as-non-root-alternative/build.sh, examples/included-as-non-root-alternative/src/cypress.json, examples/included-as-non-root-alternative/src/cypress/integration/spec.js, examples/included-as-non-root-alternative/src/index.html, examples/included-as-non-root-alternative/test.sh
- chmod a+r on `/root` folder gives any user read permissions to use globally installed Cypress NPM module
- setting environment variable `CYPRESS_CACHE_FOLDER=/root/.cache/Cypress` forces other users to use the pre-installed binary in the root, rather than in `~/.cache`
I think this might be the future approach for making new `cypress/included` images that does not run as root by default
=> another approach to give non-root user node ability to run tests

browsers/node12.14.0-chrome79-ff71/Dockerfile, browsers/node12.14.0-chrome79-ff71/README.md, browsers/node12.14.0-chrome79-ff71/build.sh
This PR adds Node `12.14.0` and current stable versions of Chrome `79.0.3945.86` (see [here](https://chromereleases.googleblog.com/2019/12/stable-channel-update-for-chrome-os.html)) and Firefox `71.0` (see [there](https://www.mozilla.org/en-US/firefox/71.0/releasenotes/)).
=> Add Node 12.14.0 and Chrome 79 with Firefox 71

base/README.md, base/ubuntu18-node12.14.1/README.md, base/ubuntu19-node12.14.1/Dockerfile, base/ubuntu19-node12.14.1/README.md, base/ubuntu19-node12.14.1/build.sh, circle.yml, test/Dockerfile
- close #212
Interesting, but Cypress v3.8.2 runs just fine there, no XVFB problem as in https://github.com/cypress-io/cypress/issues/6184
=> Add ubuntu19 image

browsers/README.md, browsers/node13.6.0-chrome-80-ff72/Dockerfile, browsers/node13.6.0-chrome-80-ff72/README.md, browsers/node13.6.0-chrome-80-ff72/build.sh, circle.yml
- closes #219
```
node version:    v13.6.0
npm version:     6.13.6
yarn version:    1.21.1
debian version:  10.2
Chrome version:  Google Chrome 80.0.3987.87
Firefox version: Mozilla Firefox 72.0.2
git version:     git version 2.20.1
```
=> add browsers image with Chrome 80 and FF 72

browsers/node12.8.1-chrome80-ff72/Dockerfile
https://github.com/cypress-io/cypress/pull/6428 is failing because this image does not have the required codecs for FF to play video
=> Add codecs to node12.8.1-chrome80-ff72

base/README.md
Update the note about Node.js support since our min supported version has changed since 4.0 release
=> Add updated note about Node.js support to reflect 4.0 updates

browsers/README.md, browsers/node12.16.1-chrome80-ff73/Dockerfile, browsers/node12.16.1-chrome80-ff73/README.md, browsers/node12.16.1-chrome80-ff73/build.sh, circle.yml
Adds a new docker file to utilize node version 12.16.1 for Chrome and Firefox browsers.
=> Add cypress/browsers:node12.16.1-chrome80-ff73

README.md, generate-included-image.js
- close #270 
- `cypress/included` images will have 3 env variables set
we should also set these variables for the new `/browsers` images
=> add note about shared memory

browsers/node10.16.3-chrome80-ff73/Dockerfile, browsers/node10.16.3-chrome80-ff73/README.md, browsers/node10.16.3-chrome80-ff73/build.sh, circle.yml, generate-config.js
- if the browsers image has `-ffYY` name, then validate Firefox with version `YY...` is installed
- run Cypress tests inside a test Docker image using Electron browser, then Chrome (if installed), then Firefox (if installed)
=> Validate ff better

browsers/README.md, browsers/node12.13.0-chrome80-ff74/Dockerfile, browsers/node12.13.0-chrome80-ff74/README.md, browsers/node12.13.0-chrome80-ff74/build.sh, circle.yml
`node12.13.0-chrome80-ff73` is based on Debian Stretch (which cypress/base:12.13.0 is based on), but we need Debian Buster for cypress-io/cypress#6555
=> add node12.13.0-chrome80-ff74

browsers/README.md, browsers/node14.10.1-edge88/Dockerfile, browsers/node14.10.1-edge88/README.md, browsers/node14.10.1-edge88/build.sh, circle.yml, generate-config.js
=> add a browser image with Edge browser

browsers/README.md, browsers/node12.18.4-edge88/Dockerfile, browsers/node12.18.4-edge88/README.md, browsers/node12.18.4-edge88/build.sh, circle.yml, generate-config.js
=> Scaffold the kitchensink tests when testing browsers

browsers/README.md, browsers/node12.19.0-chrome86-ff82/Dockerfile, browsers/node12.19.0-chrome86-ff82/README.md, browsers/node12.19.0-chrome86-ff82/build.sh, circle.yml
This PR adds a browser image to support the current node LTS version 12.19.0 (released 06-Oct-2020) and the latest versions of Chrome (86.0.4240.111) and Firefox (82.0).
This PR is based on #389.
=> Add Browsers node12.19.0 chrome86 ff82

circle.yml, generate-config.js
- closes https://github.com/cypress-io/cypress-docker-images/issues/387
- closes #411 
- separate node version check command
=> Test full Kitchensink project using cypress/included image

browsers/README.md, browsers/node12.18.3-chrome87-ff82/Dockerfile, browsers/node12.18.3-chrome87-ff82/README.md, browsers/node12.18.3-chrome87-ff82/build.sh, circle.yml
newer browsers for `cypress/included:6.0.1`
=> add Node 12.18.3 and Chrome 87 and FF 82

generate-included-image.js
Updates the packages in the newly generated `cypress/included` images during build to avoid security vulnerabilities. 
Fixes https://github.com/cypress-io/cypress-docker-images/issues/446
=> Add apt upgrade to generated cypress/included-image (#446)

examples/included-as-non-root-mapped/Dockerfile
This implements the fix proposed by @danieleades here: https://github.com/cypress-io/cypress-docker-images/issues/287#issuecomment-717158878
=> Update example `included-as-non-root-mapped` (fixes #287)

generate-base-image.js, generate-included-image.js
As experienced in #436, Node and NPM versions can be out of sync and it may seem odd, while there is already a version of NPM coming with Node, to force a version of Node while upgrading to a newer version of NPM.
This PR therefore removes the `RUN install npm@latest` script from `generate-base-image.js`
=> Remove npm@latest install in generate-base-image script

generate-base-image.js
#456 added the call to apt clean, but unfortunately missed a line continuation. This leads to invalid syntax in the generated Dockerfile.
No base image Dockerfile has been added to the repository since that change, so no changes to existing Dockerfiles are necessary.
=> Add missing line continuation to base Dockerfile generator

browsers/README.md, browsers/node14.17.0-chrome88-ff89/Dockerfile, browsers/node14.17.0-chrome88-ff89/README.md, browsers/node14.17.0-chrome88-ff89/build.sh, buildspec.yml, circle.yml
Need to publish  an image with  Chrome 88 to test performance before Chrome version 89.0.4330.0 which introduced video frame capture changes.
Need this for my video tests.
=> Add cypress/browsers:node14.17.0-chrome88-ff89

browsers/README.md, browsers/node14.15.0-chrome96-ff94/README.md
Adds a missing entry on the README file for the node14.15.0-chrome96-ff94 image and correct the name on the Dockerfile README
=> Fix README files on cypress/browsers:node14.15.0-chrome96-ff94

scripts/generate-browser-image.js
I noticed that the arg referenced in the Firefox download was missing from the Dockerfile. Also, I added a check to enforce sem ver when passing in node version on browser image creation.
=> fix: add FF version to properly get download. add logic to check for proper sem ver for node version

scripts/generate-base-image.js, scripts/generate-browser-image.js
With the changes made in #619, the trailing backslashes are not necessary for our ENV declarations.
See recent failure [here](https://app.circleci.com/pipelines/github/cypress-io/cypress-docker-images/817/workflows/06095d6b-47da-4139-ad07-12e6d7f013d7/jobs/37096).
> Error response from daemon: failed to parse Dockerfile: Syntax error - can't find = in "ENV". Must be of the form: name=value
I generated new base/browser packages and built the images locally to ensure they built correctly with these PR changes. The browsers script actually worked okay, but I updated to be consistent with the other.
=> fix: Update generated ENV to account for syntax change

scripts/generate-config.js
Updating the generation script to support three digit versions now that Chrome has hit v100. FF/Edge checks were also updated, they'll hit 100 soon.
=> fix: Support three-digit browser versions in circle config generation

circle.yml, included/10.3.1/Dockerfile, scripts/__tests__/__snapshots__/generate-config-snapshots.test.js.snap, scripts/generate-included-image.js, scripts/includes/circle-header.yml
In CI, we cross-build `linux/arm64` from `linux/amd64` using QEMU. It seems like QEMU doesn't support Electron (I'm guessing for the same reasons QEMU doesn't support Chromium), since this error results from running `cypress verify` in QEMU:
```
Command was killed with SIGSEGV (Segmentation fault): /root/.cache/Cypress/10.3.1/Cypress/Cypress --no-sandbox --smoke-test --ping=342
```
This PR updates the cross-build to pass a new buildArg, `CI_XBUILD`, which lets the Dockerfile know it's being cross-built. This causes the `verify` step to be skipped in the cross-built `arm64` build process. This seems safe since we are also running a real `arm64` build as a pre-requisite to the build+push job. Dockerfile manually tested to work with cross-building in CI via SSH.
This will enable the 10.3.1 …
=> chore: fix cypress/included cross-build

.prettierrc, scripts/__tests__/__snapshots__/generate-config-snapshots.test.js.snap, scripts/generate-config.js
I think this is causing CircleCI to fail [here](https://app.circleci.com/pipelines/github/cypress-io/cypress-docker-images/992/workflows/ef8ab5cc-1600-4814-8988-f28bbca84edc/jobs/37713) because it's not in an existing working directory. Also, the `dockerName` does not exist as is. It should be [cypress/browsers](https://hub.docker.com/r/cypress/browsers/).
The other changes are stylistic. The const return value change is [here](https://github.com/cypress-io/cypress-docker-images/pull/713/files#diff-4572eb49b4d6810989d89c931ba501b12276c24a8e4c5d5c0ab577611e42d3abR26).
=> fix: update dockerName and workingDirectory values to properly reflect browsers and not browser

circle.yml, scripts/__tests__/__snapshots__/generate-config-snapshots.test.js.snap, scripts/generate-config.js
Fixes the build issue for the `node16.14.2-slim-chrome103-ff102` browser image.
=> fix: update circle.yml with proper dockerName and workingDirectory values. dry up getImageType calls.

circle.yml
Previously i wasn't including the / between the aws prefix and the docker name. leading to 'awscypress/factory' instead of 'aws/cypress/factory'.
=> fix: update ci to include a '/' for pushing aws

factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
The user in this PR https://github.com/cypress-io/cypress-docker-images/pull/809#issuecomment-1398748399 is requesting that we include the procps dependency to install the ps command. The `ps` command doesn't appear to be used by cypress directly for linux (it is used by in darwin), however we do use `ps` in the [start-server-and-test](https://github.com/bahmutov/start-server-and-test) example repo linked from our [docs](https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server). [Previously](https://github.com/cypress-io/cypress-docker-images/pull/645) we added the `procps` dep to the base docker image.
When building out the cypress/factory docker container I specifically tried to only include dependencies used directly by cypress to minimize image size. In this …
=> fix: add ps command

factory/.env
Bumps cypress to `12.4.0` for `12.4.0` release
=> chore: update cypress version to 12.4.0 in factory/.env

factory/.env, factory/factory.Dockerfile
Users have requested use of the curl command. Typically we wouldn't add dependencies that aren't directly used by cypress, but upon investigation, not cleaning up the curl command adds less than a MB to the final package size.
=> dep: don't remove curl

factory/README.md
Running `docker compose up` using the configuration mentioned in the [`README.md`](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md#in-docker-composeyml) file, docker returns the following error:
```
services.test Additional property args is not allowed
```
Docker documentation refers that `args` are configuration options that are applied at build time.
- Moved the `args` argument under the `build` attribute
- https://docs.docker.com/compose/compose-file/compose-file-v3/#build
=> docs(factory): update docker-compose.yml configuration

factory/.env
Security update Node.js 18
https://nodejs.org/en/blog/vulnerability/february-2023-security-releases/
=> Bump Node.js 18.14.1

factory/CHANGELOG.md
I've forgotten to update the change log for the past couple of cypress/factory releases.
=> chore: update change log for cypress/factory

factory/.env
Bump the factory to Cypress `12.8.1` and update browsers to latest
=> chore: bump cypress version to 12.8.1 and bump browsers to mirror latest

factory/.env
updates the docker factory (currently failing since version does not exist)
=> chore: bump cypress to 12.9.0 and update browsers

circle.yml, factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
We accidentally removed the git binary from the images. This restores the binary and adds a test to make sure we don't lose it again.
affected packages will be re-released
* cypress/browsers:node-18.14.1-chrome-111.0.5563.110-1-ff-111.0-edge-111.0.1661.51-1
* cypress/browsers:node-18.14.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
* cypress/included:cypress-12.8.1-node-18.14.1-chrome-111.0.5563.110-1-ff-111.0-edge-111.0.1661.51-1
* cypress/included:cypress-12.9.0-node-18.14.1-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.54-1
* cypress/included:12.9.0
=> fix: Missing git binary

factory/.env, factory/CHANGELOG.md, factory/installScripts/chrome/install-chrome-version.js, factory/installScripts/edge/install-edge-version.js, factory/installScripts/firefox/install-firefox-version.js, factory/installScripts/webkit/install-webkit-version.js
https://github.com/cypress-io/cypress-docker-images/issues/867
Prior to this change the install scripts explicitly check for arm64 arch and short-circuit on the browser install scripts since there are no linux/arm64 binaries available. However, this assumes that the only other target arch is x64, preventing the image from being successfully build on other platforms. For example, the node install script supports a variety of architectures, including ppc64le, s390x, etc.
Update the install scripts to check for supported platforms instead, this is mostly x64, with the exception being webkit which is available on both x64 and arm64. For all other values, short-circuit as before.
This means that the factory image can now be built for additional platforms using docker buildx for example without …
=> Update factory install scripts to check for supported arch

circle.yml, factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
Install ssh client to enable git cloning via ssh without falling back to CI's native git client
Fixes: #846
=> feat: add ssh

included/README.md
The Gitlab example is very old and outdated, so it's removed.
The GitHub Action repo is also updated - just going to link to our active github-action repo which has a docker example.
=> Remove example of Gitlab CI, link to GitHub repo for GH action example

factory/.env
This PR updates the `factory/.env` file to use `12.11.0`
=> chore: update image for release 12.11.0

factory/.env
This PR updates the `factory/.env` file to use 12.12.0 and newest browser versions.
=> chore: update image for release 12.12.0

factory/.env
This PR updates the factory/.env file to use Cypress v12.15.0 and newest browser versions.
=> chore: cypress v12.15.0 release updates

factory/.env
Use Cypress 12.16.0 as default
=> chore: 12.16.0 release

README.md
closes #913
This PR updates the main [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) file which previously listed outdated versions as being default. It reworks these sections and provides some other corrections and improvements.
The outdated "Default" column has been removed. Instead a separate example list is provided which does not need to be updated on every release. It serves as a relatively recent list of example tagged images and explains the meanings of the tags.
It also aligns some naming according to website reference documentation conventions:
- NPM => npm (see https://docs.npmjs.com/)
- Dockerhub => Docker Hub (see https://docs.docker.com/docker-hub/)
- Node => Node.js (see https://nodejs.org/en/docs)
cc: @mjhenkes
=> docs: rework README references to tags and version

base/README.md
This PR removes an outdated statement in [base/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md)
- Image `cypress/base:12` is tagged [`latest`](https://hub.docker.com/r/cypress/base/tags/)
which is no longer true. The tag `latest` is used for the literal latest version. For example at the time of writing:
- [cypress/base:18.16.0](https://hub.docker.com/layers/cypress/base/18.16.0/images/sha256-d00c441748e2f1b79d4002bddafe6628f9f9f5458a8a3c66697e622600dc5ad5) is tagged [cypress/base:latest](https://hub.docker.com/layers/cypress/base/latest/images/sha256-d00c441748e2f1b79d4002bddafe6628f9f9f5458a8a3c66697e622600dc5ad5).
=> docs: remove outdated base/README latest tag reference

factory/.env, factory/CHANGELOG.md
Security update Node.js 18.16.1
https://nodejs.org/en/blog/vulnerability/june-2023-security-releases
=> bump node version due to node update

factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile, factory/installScripts/edge/default.sh, factory/installScripts/node/default.sh
BREAKING CHANGE: the cypress docker factory by default will now use node version 20.5.0. For node 18, please use v2
Uses node `v20.5.0` by default which is the current node. factory `v2` will be used for 18 which is current LTS
=> BREAKING CHANGE: factory to use nodejs v20

README.md
Per the discussion [here](https://github.com/cypress-io/github-action/pull/938)
And [here](https://github.com/cypress-io/cypress-docker-images/issues/871)
I have been asked to move my changes from the first link into this PR here to help others troubleshoot potential issues when using firefox in these images.
=> Update README.md to talk about non-root user for firefox per #938 in the github-action repo

factory/.env
Bumps the Cypress version to `13.1.0`
=> feat: bump cypress version in docker factory

factory/.env, factory/CHANGELOG.md
Also bumps the factory version from `3.0.0` to `3.1.0` as have updated the default factory node version
=> chore: bump the cypress version for image release and update browsers to latest

factory/installScripts/node/default.sh
Fixes #939 by adding the new release key introduced in that release.
Also syncs the rest of the script with the [upstream Dockerfile from docker-node](https://github.com/nodejs/docker-node/blob/main/20/bookworm-slim/Dockerfile)
=> chore: sync Node.js install script with upstream install

factory/.env
=> chore: bump Cypress version to 13.3.0

factory/.env
=> chore: bump Cypress version to 13.3.1

factory/.env, factory/CHANGELOG.md
Bump default node version from v20.6.1 to v20.8.1 as it is a security release (and the new LTS since October 24):
- https://nodejs.org/en/blog/release/v20.8.1
=> chore: bump node version to 20.8.1

factory/.env, factory/CHANGELOG.md
* Updated `CYPRESS_VERSION` to `13.3.3`
* Updated `FACTORY_DEFAULT_NODE_VERSION` to `20.9.0`
Note: `FACTORY_VERSION` `3.2.0` hasn't released yet, so there is no need to update the version for this change.
=> chore: cypress 13.3.3 release updates

factory/.env, factory/CHANGELOG.md, factory/installScripts/chrome/default.sh
Removing the extra `d` from the end of temp file name
=> Fix temp deb file name

factory/.env, factory/CHANGELOG.md
This PR updates:
- Node to `20.10.0` ([current LTS](https://nodejs.org/en))
=> chore: image for node 20.10.0

factory/.env
updates the docker factory cypress version to 13.6.3
=> chore: update CYPRESS_VERSION in factory to 13.6.3

factory/.env, factory/CHANGELOG.md
includes updated browsers, cypress version, and node LTS
=> chore: bump factory 3.5.0

factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
This is an attempt to solve: https://github.com/cypress-io/cypress-docker-images/issues/1013
This is based on the documentation in README/CONTRIBUTING, but I might have misunderstood something, please let me know if that is the case.
After making these changes, I ran the following (for some reason, the images built with 'included' does not seem to work, and I am unsure why): 
```
$docker compose build factory
[+] Building 2.2s (8/8) FINISHED                                                                                                                                                                                             docker:default
=> [factory internal] load build definition from factory.Dockerfile …
```
=> Add unzip to factory

CONTRIBUTING.md
There weren't instructions on how to publish the internal base/browser images to dockerhub, so initially I assumed it would be done automatically. After going through manually publishing them, I've added docs on how to do this for people in the future.
=> docs: Add instructions on publishing images auto/manual

factory/.env
updates docker factory with cypress `13.6.5` and updates browsers to latest stable
=> update factory for 13.6.5 cypress release with updated browsers

factory/.env, factory/CHANGELOG.md
updates cypress to 13.7.1 and bumps the browser images to latest available. Also bumps node from `20.11.0` to `20.11.1` which requires a patch bump.
=> feat: release 13.7.1

factory/.env, factory/CHANGELOG.md
updates Cypress to 13.7.3 and updates browsers to latest and node to latest LTS
=> chore: release 13.7.3 

factory/.env
also includes updating firefox from 125.0.1 to 125.0.2
=> chore: update factory to cypress 13.8.1

browsers-internal/node18.17.1-chrome124-ff125-edge/Dockerfile, browsers-internal/node18.17.1-chrome124-ff125-edge/README.md, browsers-internal/node18.17.1-chrome124-ff125-edge/build.sh, browsers-internal/node18.17.1-chrome124-ff125-edge/global-profile.sh, browsers-internal/node18.17.1-chrome124-ff125/Dockerfile, browsers-internal/node18.17.1-chrome124-ff125/README.md, browsers-internal/node18.17.1-chrome124-ff125/build.sh, browsers-internal/node18.17.1-chrome124-ff125/global-profile.sh
Adds the Chrome 124 / Firefox 125 image to update the browsers used inside of CircleCI inside the cypress app repo (see https://github.com/cypress-io/cypress/pull/29391). Publishing is handled manually so these files are for archival purposes.
=> chore: add internal docker images for chrome 124 and firefox 125

CONTRIBUTING.md, base-internal/ubuntu24-node18/Dockerfile, base-internal/ubuntu24-node18/README.md, base-internal/ubuntu24-node18/build.sh
since Nobel Numbat is available, we should add the image under test in the [cypress repo](https://github.com/cypress-io/cypress/blob/develop/system-tests/test-binary/ci_environments_spec.ts#L34) since we test the last two major versions unofficially of ubuntu. See related https://github.com/cypress-io/cypress/pull/29412
=> chore: add ubuntu 24 image

package.json
[package.json](https://github.com/cypress-io/cypress-docker-images/blob/master/package.json) contains several script definitions which refer to script sources that no longer exist.
https://github.com/cypress-io/cypress-docker-images/blob/b9525720b9e4e44ee7ded7f974dae89cc0dfd6f3/package.json#L10-L14
- The script sources were removed as part of PR https://github.com/cypress-io/cypress-docker-images/pull/812
Remove the following obsolete script definitions from [package.json](https://github.com/cypress-io/cypress-docker-images/blob/master/package.json):
- `build`
- `add:base`
- `add:browser`
- `add:included`
=> chore: remove obsolete script definitions

README.md
[README > Firefox not found](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#firefox-not-found) refers to outdated GitHub JavaScript action versions, which use the deprecated / end-of-life `node16` version:
```yml
name: E2E in custom container
on: push
jobs:
cypress-run:
runs-on: ubuntu-22.04
container:
image: cypress/browsers:node18.12.0-chrome106-ff106
options: --user 1001
steps:
- uses: actions/checkout@v3
- uses: cypress-io/github-action@v5
with:
browser: firefox
```
- [actions/checkout@v3](https://github.com/actions/checkout/tree/v3) using `node16`
- [cypress-io/github-action@v5]()
Update the example in [README > Firefox not found](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#firefox-not-found) to use latest and supported …
=> docs: update README Firefox not found example

factory/docker-compose.yml, factory/test-project/docker-compose.yml
The repo uses an obsolete `version` file format definition in Docker compose files:
- [factory/docker-compose.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/docker-compose.yml) specifies `version: '3.8'` file format.
- [factory/test-project/docker-compose.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/docker-compose.yml) specifies `version: '3'` file format.
Docker Compose outputs the following warning message when run:
> `version` is obsolete
The `version` definition belongs to the Compose V1 specification and is no longer supported. Compose V1 is no longer included in current releases of Docker Desktop and the final release was in May 2021.
Compose V2, the current version, released in 2020, ignores the `version` …
=> chore: remove obsolete compose v1 file format version

factory/.env, factory/CHANGELOG.md
updates browsers and node version along with Cypress 13.10.0 for the docker factory
=> update factory with cypress 13.10.0 release

factory/test-project/cypress.config.js, factory/test-project/cypress/e2e/2-advanced-examples/actions.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/connectors.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/cookies.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/cypress_api.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/files.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/navigation.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/storage.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/utilities.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/viewport.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/waiting.cy.js
The example specs in [factory/test-project](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/test-project) are out of date and not aligned to Cypress `13.10.0`. There have been a number of corrections made to the upstream source [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink).
- Recreate [factory/test-project/cypress](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/test-project/cypress)
=> chore: update to cypress 13.10.0 example specs

factory/test-project/package.json
[factory/test-project/package.json](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/package.json) has several minor issues:
The `description` and `author` fields are blank. The `license` field is incorrectly showing `ISC`.
Make corrections to [factory/test-project/package.json](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/package.json):
1. Add a description "Test project for Cypress Docker images"
2. Remove the `author` and `license` fields. The test-project is never published separately and the repo itself is licensed with the [MIT license](https://github.com/cypress-io/cypress-docker-images/blob/master/LICENSE)
On Ubuntu `22.04.4` LTS, Node.js `20.13.1` LTS
execute:
```shell
cd factory/test-project
npm install …
```
=> chore: update test-project package.json

included/README.md
The [included/README > Building and testing](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md#building-and-testing) section includes outdated instructions to build a new image using the removed script `add:included`. The instructions appear to be targeted to contributors, as they describe pushing to Cypress' Docker Hub.
- PR https://github.com/cypress-io/cypress-docker-images/pull/812 replaced the process to generate new images, including updating the [CONTRIBUTING](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md) document to include instructions on generating all types of images.
- PR https://github.com/cypress-io/cypress-docker-images/pull/1055 removed the obsolete script definitions.
Completely remove the outdated and …
=> docs: remove included/readme image generation instructions

CONTRIBUTING.md
[CONTRIBUTING > Multi-Architecture Support](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#multi-architecture-support) contains the paragraph:
> A current limitation is that no `arm64` images have browser binaries - see https://github.com/cypress-io/cypress-docker-images/issues/695 for details. [`global-profile.sh`](https://github.com/cypress-io/cypress-docker-images/blob/master/scripts/for-images/global-profile.sh) is placed in `/etc/bash.bashrc`, so Arm Docker users will see a warning about this limitation.
The second sentence links to https://github.com/cypress-io/cypress-docker-images/blob/master/scripts/for-images/global-profile.sh and produces a "404 -page not found" error.
- PR https://github.com/cypress-io/cypress-docker-images/pull/812 removed the …
=> docs: remove global profile from contributing

included/README.md
The document [included/README](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) is outdated. It is at a Cypress legacy level using Cypress `9.4.1` (pre Cypress `10.x`).
1. Examples use legacy Cypress Docker image `cypress/included:9.4.1`. They will only run against a legacy Cypress project (Cypress < `10.x`).
2. The linked blog [How to Run Cypress in Docker With a Single Command](https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command) from May 2, 2019 is based on outdated and legacy information.
3. The linked blog [End-to-End Testing Web Apps: The Painless Way](https://mtlynch.io/painless-web-app-testing/) contains the text "Update (2022-10-25): I no longer recommend Cypress for end-to-end testing web applications. For new …
=> docs: refresh included readme

factory/.env, factory/CHANGELOG.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/1036
- supersedes https://github.com/cypress-io/cypress-docker-images/pull/1037
- The stable version of Yarn v1 Classic has changed from `1.22.19` to `1.22.22`
- If Yarn v1 Classic `1.22.19` is used under Node.js `21` or later, it shows deprecation warnings. This issue is resolved in the stable version `1.22.22` (see issue https://github.com/yarnpkg/yarn/issues/9013).
In [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env)
1. Update `FACTORY_VERSION` to `3.5.7`
2. Update `YARN_VERSION` to `1.22.22`
- Yarn release [v1.22.22](https://github.com/yarnpkg/yarn/releases/tag/v1.22.22)
- https://classic.yarnpkg.com/latest-version shows `1.22.22` to be the `latest` (`stable`) version
- …
=> chore(deps): update to yarn 1.22.22

base/README.md
[base/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md) contains outdated information:
- base images do not install the latest versions of NPM & Yarn
- npm is bundled with Node.js. Often the bundled version of npm lags behind the latest version of npm.
- Yarn is not the latest version. It is the frozen Yarn v1 Classic version defined in [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) (currently `1.22.19`). The latest Yarn Modern version is [4.2.2](https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.2.2).
- The sections referring to Node.js are discussing legacy Cypress versions and versions of Node.js which are no longer under support
Remove the outdated information from …
=> docs: remove base readme obsolete information

CONTRIBUTING.md
[CONTRIBUTING.md](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md) fails `markdown-link-check`.
```text
ERROR: 5 dead links found!
[✖] /factory/README.md → Status: 400
[✖] /factory/factory.Dockerfile → Status: 400
[✖] /factory/installScripts/ → Status: 400
[✖] /factory/CHANGELOG.md → Status: 400
[✖] /factory/.env → Status: 400
```
Make failing links relative e.g.
`/factory/README.md` => `./factory/README.md`
```shell
npm ci
npx markdown-link-check CONTRIBUTING.md
```
=> chore: fix failing contributing links

browsers/README.md
[browsers/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md) contains outdated information:
- https://chromium.cypress.io/ is no longer active as a source of Chromium versions
- The explanation of tags in [browsers/README.md > Naming scheme](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md#naming-scheme) and in [browsers/README.md > Tags](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md#tags) is outdated and duplicates information in [README > Tag Selection](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#tag-selection)
- The section [browsers/README.md > Other images](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md#oth …
=> docs: remove browsers readme obsolete information

README.md, included/README.md
In the [README > Examples](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#examples) section ...
- The first paragraph
- is not referring to examples, so it is misplaced in this section
- misleadingly says you need to install Cypress which is not true for `cypress/included`
- The link to [Check out our docs for examples.](https://on.cypress.io/docker) links to https://on.cypress.io/docker where there are no examples to be found.
- The following paragraph refers to an outdated legacy blog (see also PR https://github.com/cypress-io/cypress-docker-images/pull/1070):
> If you want to use the `cypress/included` image, read [Run Cypress with a single Docker command](https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/)
- The set of 4 …
=> docs: fix README Examples issues

README.md
[README > Common problems > Cannot run post-install hook](https://github.com/cypress-io/cypress-docker-images#cannot-run-post-install-hook) recommends using  `npm install --unsafe-perm`.
Currently the minimum supported version of Node.js is `18.x`. The note relates to `npm` rather than `Node.js` itself. `npm` is bundled in `Node.js`.
The lowest Node.js `18.x` version is [Node.js 18.0.0](https://nodejs.org/en/blog/release/v18.0.0) which bundles npm `8.6.0`.
The [npm CHANGELOG 7.0.0 > All Lifecycle Scripts](https://github.com/npm/cli/blob/release/v7/CHANGELOG.md#all-lifecycle-scripts) says:
> The `user`, `group`, `uid`, `gid`, and `unsafe-perms` configurations are  no longer relevant. When npm is run as root, scripts are always run with the effective `uid` and `gid` of the working directory …
=> docs: remove obsolete problem post-install hook

factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
- follows on from https://github.com/cypress-io/cypress-docker-images/pull/1077
https://github.com/cypress-io/cypress-docker-images/blob/b32255e644878bdbdf88e209f827c2ae47e24095/factory/factory.Dockerfile#L14-L15  sets an environment variable:
```text
npm_config_unsafe_perm: true
```
This environment variable is obsolete.
The lowest supported Node.js version is [Node.js 18.0.0](https://nodejs.org/en/blog/release/v18.0.0) which bundles npm `8.6.0`. (See [Node.js Release schedule](https://github.com/nodejs/release#release-schedule).)
The [npm CHANGELOG 7.0.0 > All Lifecycle Scripts](https://github.com/npm/cli/blob/release/v7/CHANGELOG.md#all-lifecycle-scripts) says:
> The `user`, `group`, `uid`, `gid`, and `unsafe-perms` configurations are  no longer relevant. When npm is run as root, …
=> fix: remove obsolete environment variable npm_config_unsafe_perm

CONTRIBUTING.md
The [CONTRIBUTING > Minimize image sizes](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#minimize-image-sizes) document section is outdated concerning Debian base versions.
The default `BASE_IMAGE` is determined by the same named property in the [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) file.
When `cypress/factory` was introduced through PR https://github.com/cypress-io/cypress-docker-images/pull/812 in January 2023 `BASE_IMAGE` was set to `debian:bullseye-slim` (Debian 11).
Since PR https://github.com/cypress-io/cypress-docker-images/pull/1057 on May 30, 2024 `BASE_IMAGE` is set to `debian:12-slim` (codename `bookworm`).
The prior PR https://github.com/cypress-io/cypress-docker-images/pull/597 from March …
=> docs: update contributing image size section

included/README.md
The [included/README > Debug](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md#debug) section includes a link to https://on.cypress.io/debugging#Print-DEBUG-logs. The section `Print-DEBUG-logs` is however no longer at that location, so the link does not present the expected material. No error message is given in this case, since the page exists and only the bookmark is missing from the page.
The intended section resides at https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs.
Since the vanity-link<br>https://on.cypress.io/troubleshooting#Print-DEBUG-logs also leads to<br>https://docs.cypress.io/guides/references/troubleshooting#Print-DEBUG-logs, replace the incorrect link with the vanity …
=> docs: fix link to print-debug-logs

included/README.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/589
This issue concerns the syntax used in the [included/README](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) examples for [Bind mounts](https://docs.docker.com/storage/bind-mounts/) of Cypress projects using the CLI option `-v` and the environment variable `PWD` (Print Working Directory), for example:
> `$ docker run -it -v $PWD:/e2e -w /e2e cypress/included:13.10.0`
1. If the path of the current working directory represented by `PWD` contains spaces, then the command fails with an error message:
```text
docker: invalid reference format
```
2. If the syntax `-v $PWD:/e2e` is used on Windows PowerShell then the command fails with an error message:
```text
At line:1 char:21
+ $ docker …
```
=> docs: migrate examples to relative bind mounts

browsers-internal/node18.18.2-chrome125-ff126-edge/Dockerfile, browsers-internal/node18.18.2-chrome125-ff126-edge/README.md, browsers-internal/node18.18.2-chrome125-ff126-edge/build.sh, browsers-internal/node18.18.2-chrome125-ff126-edge/global-profile.sh, browsers-internal/node18.18.2-chrome125-ff126/Dockerfile, browsers-internal/node18.18.2-chrome125-ff126/README.md, browsers-internal/node18.18.2-chrome125-ff126/build.sh, browsers-internal/node18.18.2-chrome125-ff126/global-profile.sh
adds 18.18.2 chrome 125 firefore 126 related browser images for the cypress app's update to Electron 28
=> chore: add 18.18.2 chrome 125 firefore 126 related browser images

included/README.md
The example [included > Restrict CPU](https://github.com/cypress-io/cypress-docker-images/tree/master/included#restrict-cpu)
> docker run -it -v .:/e2e -w /e2e --cpus=0.02   -e DEBUG=cypress:launcher --entrypoint=cypress   cypress/included:13.10.0 info
takes a long time to run, produces no debug output and unnecessarily uses bind mount.
In the example [included > Restrict CPU](https://github.com/cypress-io/cypress-docker-images/tree/master/included#restrict-cpu)
1. Remove the bind mount `-v .:/e2e -w /e2e`
2. Increase CPUs available by factor of 10 to `--cpus=0.2`
3. Set the `DEBUG` environment variable to `DEBUG=cypress:launcher:*`
to use:
```shell
docker run -it --cpus=0.2 -e DEBUG=cypress:launcher:* --entrypoint=cypress cypress/included:13.10.0 info
```
On Ubuntu `24.04.4` LTS
- …
=> docs: fix restrict cpu example

circle.yml
- relates to issue https://github.com/cypress-io/cypress-docker-images/issues/1093
Breaking changes in https://github.com/docker/buildx have caused a compatibility issue with the 4 year old [docker-image-not-found@1.1.1](https://www.npmjs.com/package/docker-image-not-found/v/1.1.1) from the https://github.com/cypress-io/docker-image-not-found repo.
`docker-image-not-found` is unable to parse the manifest and cannot determine whether a version has been published or not.
See also
- https://github.com/docker/buildx/issues/1964
- https://github.com/docker/buildx/issues/1509
- Revert PR https://github.com/cypress-io/cypress-docker-images/pull/1079
| CircleCI Component                                                                    | PR 1709                 | revert to               |
| …
=> Revert "ci: update circleci runner (#1079)"

factory/.env, factory/CHANGELOG.md
- updates Node LTS to `20.14.0`
- chrome to `125.0.6422.141-1`
- edge to `125.0.2535.85-1`
- firefox to `126.0.1`
- cypress to `13.11.0`
=> chore: release cypress 13.11.0 related docker images and update factory

README.md
[README > Common problems > Blank screen in Chrome](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#blank-screen-in-chrome) contains the following advice:
>When running headed tests with X11 forwarding in Cypress v4 you might see a blank Chrome screen. Try disabling memory sharing by setting the following environment variables:
>
>```shell
>export QT_X11_NO_MITSHM=1
>export _X11_NO_MITSHM=1
>export _MITSHM=0
>```
>
> - See [issue #270](https://github.com/cypress-io/cypress-docker-images/issues/270)
- [issue #270](https://github.com/cypress-io/cypress-docker-images/issues/270) was closed in March 2020.
---
- The variables mentioned have progressed through to
https://github.com/cypress-io/cypress-docker-images/blob/47149ea3d5b58dae09139ae5a523d7ffd129bc91/factory/fa …
=> docs: remove outdated blank screen issue

included/README.md
The following examples in [included/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) will not run, since they are missing bind mounts to a Cypress project:
- [Arguments > run a single spec](https://github.com/cypress-io/cypress-docker-images/tree/master/included#arguments)
- [Entry with arguments](https://github.com/cypress-io/cypress-docker-images/tree/master/included#entry-with-arguments)
- [Arguments > run a single spec](https://github.com/cypress-io/cypress-docker-images/tree/master/included#arguments)
- Add `-v .:/e2e -w /e2e` to the command line.
- Change the spec path and name to `cypress/e2e/spec.cy.js` for compatibility with the default Cypress example spec name.
- [Entry with …
=> docs: add missing bind mounts

circle.yml, factory/.env, factory/docker-compose.yml
- depends on https://github.com/cypress-io/cypress-docker-images/issues/1083
- closes https://github.com/cypress-io/cypress-docker-images/issues/1082
- closes https://github.com/cypress-io/cypress-docker-images/issues/1050
- supersedes https://github.com/cypress-io/cypress-docker-images/pull/1090
Current Cypress Docker images which include Node.js `18.x` are using [18.16.1](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2023-06-20-version-18161-hydrogen-lts-rafaelgss) which is now almost one year old.
The current latest Node.js 18.x version is [18.20.3](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#2024-05-21-version-18203-hydrogen-lts-richardlau) released on May 21, 2024.
Refresh Current Cypress Docker images `cypress/base`, …
=> feat: publish set of node.js 18.20.3 images

CONTRIBUTING.md
The Docker best practice article referenced in [CONTRIBUTING > Omit apt-get clean](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#omit-apt-get-clean) has moved to https://docs.docker.com/build/building/best-practices/#apt-get
Update the link `Best practices for writing Dockerfiles` in [CONTRIBUTING > Omit apt-get clean](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#omit-apt-get-clean) to Docker [Manuals > Docker Build > Building images > Best practices > Dockerfile instructions > RUN > apt-get](https://docs.docker.com/build/building/best-practices/#apt-get) and consolidate the reference into one place in this section.
=> docs: update Docker apt-get best practice reference

README.md, base/README.md, browsers/README.md, factory/README.md, included/README.md
The README files deal inconsistently with information about which tags are used by Cypress Docker images:
- [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md)
- [factory/README](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md)
- [base/README](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md)
- [browsers/README](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md)
- [included/README](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md)
Tags are created through [factory/docker-compose.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/docker-compose.yml). …
=> docs: add tag infos to readme files

base/README.md, examples/basic/Dockerfile.base, examples/basic/README.md, examples/basic/cypress.config.js, examples/basic/cypress/e2e/spec.cy.js, examples/basic/index.html, examples/basic/package-lock.json, examples/basic/package.json
- contributes to resolution of https://github.com/cypress-io/cypress-docker-images/issues/1109
The [base/README](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md) is enhanced to describe how to use the Cypress Docker image `cypress/base` in
- interactive mode
- building a new image from `cypress/base`
Supporting files are added to the [examples](https://github.com/cypress-io/cypress-docker-images/tree/master/examples) directory.
=> docs: add cypress/base examples

CONTRIBUTING.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/829
The following documents are not clear enough about when a user should use cypress/factory and when publishing to Cypress' Docker Hub is appropriate:
- [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#cypressfactory)
- [CONTRIBUTING](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md)
- [factory/README](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md)
Add a note to [CONTRIBUTING](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md) to describe publishing restrictions and link to [factory/README](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md) for individual …
=> docs: add note for publishing and cypress/factory

browsers/README.md, examples/basic/Dockerfile.browsers
- contributes to resolution of https://github.com/cypress-io/cypress-docker-images/issues/1109
The [browsers/README](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md) is enhanced to describe how to use the Cypress Docker image `cypress/browsers` in
- interactive mode
- building a new image from `cypress/browsers`
A `Dockerfile` is added to the [examples/basic](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/basic) directory.
=> docs: add cypress/browsers examples

factory/README.md
Use of terms in [factory/README](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md) is not consistent.
The term "container" does not conform to the [Docker glossary definition](https://docs.docker.com/glossary/). The build process results in a read-only "image", whereas the run process creates a read/write "container". A Docker "image" is sometimes also referred to as a "container image".
Different terms `args` / `ARG` / `env` are used when referring to [ARG](https://docs.docker.com/reference/dockerfile/#arg) parameters used in a `Dockerfile`.
Branded names are referred to with incorrect capitalization.
> Docker images are the basis of [containers](#container).  An Image is an ordered collection of root filesystem changes and the corresponding execution …
=> docs: align terms in factory readme

examples/basic-mini/README.md, examples/basic-mini/cypress.config.js, examples/basic-mini/cypress/e2e/spec.cy.js, examples/basic-mini/index.html, examples/basic-mini/package-lock.json, examples/basic-mini/package.json
To avoid Cypress-version conflicts when testing with `cypress/included`, a Cypress project is needed which has no Cypress dependency defined in its `package*.json` files.
Add a the Cypress project `examples/basic-mini` configured without any Cypress version dependency.
```shell
cd examples/basic-mini
docker run -it --rm -v .:/e2e -w /e2e cypress/included
docker run -it --rm -v .:/e2e -w /e2e --entrypoint cypress cypress/included info
docker run -it --rm -v .:/e2e -w /e2e --entrypoint cypress cypress/included run --browser chrome
```
=> docs: add examples/basic-mini project - w/o Cypress version

factory/.env
updates:
chrome to `126.0.6478.114-1`
edge to `126.0.2592.61-1`
firefox to `127.0.1`
cypress to `13.12.0`
=> chore: cypress 13.12.0 release

.github/workflows/example-cypress-github-action.yml, README.md
This repo contains no examples of using Cypress Docker images with the [Cypress JavaScript GitHub Action](https://github.com/cypress-io/github-action) `cypress-io/github-action`.
The [included/README](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) links to https://github.com/cypress-io/github-action#docker-image where there is only an example with `cypress/browsers:latest`. Examples for `cypress/base` and `cypress/included` are missing.
1. Add a workflow `example-cypress-github-action.yml` to run against the examples, showing each of the browsers: Electron, Chrome, Edge and Firefox. The workflow is triggered only on manual demand with `workflow_dispatch`.
2. Add a link into [README > Examples](https://github.com/cypress-io/cypress-docker-images/blob/mas …
=> docs: add cypress github action examples

CONTRIBUTING.md, factory/.env
[CONTRIBUTING > Releasing a new factory version](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#releasing-a-new-factory-version) specifies releasing a new `cypress/factory` version after changes to [factory.Dockerfile](./factory/factory.Dockerfile) or [installScripts](./factory/installScripts/). It does not mention changes to the [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) file.
In practice, changes to the following parameters in the [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) file have prompted bumping the `FACTORY_VERSION` and recording it in the [factory/CHANGELOG](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/CHANGELOG.md):
- …
=> docs: factory version bump description

README.md
The following individual README documents are not linked into the top level [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) document:
- [base/README](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md)
- [browsers/README](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md)
The top level [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) currently only refers to the:
- [included/README](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md)
- Now that these files have example content added (see PR #1110 and #1113), links to these files are added to the [README > Examples](https://github.com/cypress-io/cypress-docker-images/blob/master/ …
=> docs: add examples readme links to readme

README.md, browsers/README.md, included/README.md
- closes #1130
Information concerning Docker platform and [multi-architecture](https://docs.docker.com/contribute/style/terminology/#multi-architecture--multi-arch) support is missing from the user documentation.
- All current Cypress Docker images support `Linux/amd64` and `Linux/arm64` platforms
- `cypress/browsers` and `cypress/included` Cypress Docker images for the `Linux/arm64` platform contain no browsers
Add information about Linux Debian platform support and [Multi-architecture](https://docs.docker.com/contribute/style/terminology/#multi-architecture--multi-arch) support to the READMEs:
- [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md)
- [browsers/README](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md)
- …
=> docs: add platform information

base-internal/releases/node-20/20.15.0/Dockerfile, base-internal/releases/node-20/20.15.0/README.md, base-internal/releases/node-20/20.15.0/build.sh, browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/Dockerfile, browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/README.md, browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/build.sh, browsers-internal/releases/node-20/node20.15.0-chrome126-ff127/global-profile.sh
adds the 20.15.0 docker image and browsers images to be used within cypress CI to test the kitchensink. see https://github.com/cypress-io/cypress/pull/29771
images are already published
=> chore: add 20.15.0 internal docker images

README.md
The main [README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) contains some minor white-space formatting issues.
Use `prettier` to reformat.
```shell
npm ci
npx prettier --check README.md
```
=> docs: fix README formatting

factory/Dockerfile, factory/factory.Dockerfile
- closes https://github.com/cypress-io/cypress-docker-images/issues/1139
When running `docker compose build factory` under Docker Desktop for Linux, a warning is output:
> => [factory internal] load build definition from factory.Dockerfile
> => => transferring dockerfile: 4.84kB
> => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 4) 
Modify the following to use upper case "AS" to match the case of "FROM"
- [factory/Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/Dockerfile)
- [factory/factory.Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/factory.Dockerfile)
Ubuntu  22.04.4 LTS
Node.js v20.15.0
Docker version  27.0.3
Docker Desktop 4.31.0 (153195)
Execute the following and check that there is …
=> build: use uppercase FROM / AS combination in Dockerfile

circle.yml
The [official VS Code CircleCI extension](https://marketplace.visualstudio.com/items?itemName=circleci) reports that the workflow version in the CircleCI workflow [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) is deprecated.
```yml
workflows:
version: 2
```
See also https://discuss.circleci.com/t/circleci-2-1-config-overview/26057:
> Make sure to take the version key out of your workflows section or bad things will happen. The only version key in 2.1 is the top-level key.
Remove `version` from CircleCI [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml), `workflows` section.
=> ci: remove workflow version from circle.yml

circle.yml
The CircleCI workflow [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) selects the `circleci/node@5.0.0` Orb which is however otherwise unused in the workflow:
```yml
orbs:
node: circleci/node@5.0.0
```
Remove the unused CircleCI Orb from the CircleCI workflow [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml).
=> ci: remove unused node orb from circle.yml

circle.yml
The CircleCI workflow [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) formatting is invalid according to the [official VS Code CircleCI extension](https://marketplace.visualstudio.com/items?itemName=circleci.circleci).
The closing brackets (`]`) of `test-target` in multiple places are incorrectly indented.
Fix the indentation issues concerning `test-target` in the `workflows` section of [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml).
This is a whitespace change only. It is however significant in the [yaml](https://yaml.org/spec/1.2.2/) syntax, which uses indentation to define scope.
=> ci: correct circle.yml indentation syntax error

circle.yml
- closes https://github.com/cypress-io/cypress-docker-images/issues/1142
- closes https://github.com/cypress-io/cypress-docker-images/issues/1141
- supports resolution of issue https://github.com/cypress-io/cypress-docker-images/issues/1095
- supports resolution of issue https://github.com/cypress-io/cypress-docker-images/issues/1145
When used in the [CircleCI workflow](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow, the npm module [docker-image-not-found](https://www.npmjs.com/package/docker-image-not-found) outputs an error message "unsupported schema version 2" when attempting to check the existence of a Docker image on Docker Hub, if the image has been published with an `oci` type manifest instead of a `docker` type manifest.
In the [CircleCI …
=> ci: check image exists with Docker Hub API

circle.yml
Supports resolution of
- https://github.com/cypress-io/cypress-docker-images/issues/1145
- https://github.com/cypress-io/cypress-docker-images/issues/1095
- Docker [Buildx v0.10.0](https://docs.docker.com/build/release-notes/#0100) introduced a breaking change causing multi-architecture manifests to use `oci` instead of `docker` `imageType` formats. The release notes warn about issues with registry and runtime support. This already caused a issue in this repo (see https://github.com/cypress-io/cypress-docker-images/issues/1141). It is unknown whether allowing the manifest `imageType` to change for Cypress Docker images would cause usage issues in users' environments and it would have to be considered as a breaking change for Cypress Docker.
- This repo is currently using [Buildx …
=> build: disable default provenance attestation

circle.yml
- closes #1145
The [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow is currently using machine image `ubuntu-2204:2022.10.2` from [Circle CI Machine Images > ubuntu-2204](https://circleci.com/developer/machine/image/ubuntu-2204) which includes Node.js `16.17.1`.
This Node.js version entered [End-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on Sep 11, 2023 and so it is now unsupported.
The [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow is updated to [ubuntu-2204:2023.04.2](https://discuss.circleci.com/t/linux-machine-executor-2023-q2-update-edge-ga-release/47680):
| Image tag …
=> chore: update circleci to ubuntu-2204:2023.04.2 machine image

factory/.env, factory/CHANGELOG.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/1137
- Debian `12.6` was released on [June 29th, 2024](https://www.debian.org/News/2024/20240629) and contains vulnerability fixes which are not included in `cypress/factory:4.0.2` (current `latest`).
Update to `debian:12.6-slim` in `cypress/factory`, specifying exact version of Debian for documentation clarity of version in use.
On Ubuntu `22.04.4` LTS, Node.js `v20.15.0` LTS
Execute:
```shell
cd factory
docker compose build factory
docker compose build
```
and confirm that all images are built without errors or warnings.
Continue with
```shell
cd test-project
set -a && . ../.env && set +a
docker compose run test-factory-all-included
```
and confirm that the image builds without errors or warnings and runs successfully.
=> fix: update cypress/factory to Debian 12.6

factory/.env, factory/CHANGELOG.md
- closes #1153
- The Node.js project released a security update [Node.js v20.15.1 LTS](https://nodejs.org/en/blog/release/v20.15.1) on July 8, 2024.
In [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) update
- `FACTORY_VERSION` to 4.0.4
- `FACTORY_DEFAULT_NODE_VERSION` from `20.14.0` to `20.15.1`
=> chore(deps): update to Node.js 20.15.1

circle.yml
- supports resolution of issue https://github.com/cypress-io/cypress-docker-images/issues/1095
- Following the successful merge of PR https://github.com/cypress-io/cypress-docker-images/pull/1147, the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow is now using machine image [ubuntu-2204:2023.04.2](https://discuss.circleci.com/t/linux-machine-executor-2023-q2-update-edge-ga-release/47680) from [Circle CI Machine Images > ubuntu-2204](https://circleci.com/developer/machine/image/ubuntu-2204). This fulfils the requirement to run under a supported version of Node.js (`18.15.0`), however the Docker Engine [20.10.24](https://docs.docker.com/engine/release-notes/20.10/#201024) with Buildx …
=> chore: update circleci to ubuntu-2204:2023.10.1 machine image

factory/CHANGELOG.md
[factory/CHANGELOG.md](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/CHANGELOG.md) uses the asterisk (`*`) character for unordered lists. Prettier, since [release 1.13](https://prettier.io/blog/2018/05/27/1.13.0.html#markdown) in May 2018,  standardizes on using dash (`-`) for unordered lists.
Use `prettier` to reformat.
Note that this is a Markdown source code change only. GitHub continues to displays unordered list elements with a bullet, like
- this
```shell
npm ci
npx prettier --check factory/CHANGELOG.md
```
=> docs: fix CHANGELOG formatting

factory/.env
Firefox released versions:
- [127.0.2](https://www.mozilla.org/en-US/firefox/127.0.2/releasenotes/) on June 25, 2024
- [128.0](https://www.mozilla.org/en-US/firefox/128.0/releasenotes/) on July 9, 2024.
The repo is currently configured for Firefox [127.0.1](https://www.mozilla.org/en-US/firefox/127.0.1/releasenotes/), released on June 19, 2024.
https://github.com/cypress-io/cypress-docker-images/blob/2f47b54b7e22b1c5097d92ad8cbd70305075d39c/factory/.env#L28-L29
Update [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) to
```text
FIREFOX_VERSION='128.0'
```
=> chore(deps): update Firefox to 128

circle.yml
The [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) `push` job outputs no information about the versions of Node.js, Docker and Buildx used to build and push Cypress Docker images.
Documentation provided on the [CircleCI](https://circleci.com/developer) website regarding the content of the Ubuntu machine images is incomplete. Starting with [Docker Engine 23.0](https://docs.docker.com/engine/release-notes/23.0/) Buildx is distributed in a separate package `docker-buildx-plugin`. Since the CircleCI documentation does not list the configured version of Buildx, it is only possible to determine it by inspection of the machine image.
Add logging information for the versions of Node.js, Docker and Buildx used in the `push` job to the …
=> build: add version information to logs

circle.yml
- supports resolution of issue https://github.com/cypress-io/cypress-docker-images/issues/1095
- Following the successful merge of PR https://github.com/cypress-io/cypress-docker-images/pull/1155, the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow is now using machine image [ubuntu-2204:2023.10.1](https://discuss.circleci.com/t/linux-machine-executor-2023-q4-update/49457) from [Circle CI Machine Images > ubuntu-2204](https://circleci.com/developer/machine/image/ubuntu-2204). The Docker Engine [24.0.6](https://docs.docker.com/engine/release-notes/24.0/#2406) is however a release from September 2023 and lags behind the latest version of Docker Engine which is currently at [27.0.3](https://docs.docker.com/engine/release-notes/27.0/).
Update …
=> chore: update circleci to ubuntu-2204:2024.01.1 machine image

included/README.md
The [included/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) does not have the Docker image `ENTRYPOINT` described in the same way as `CMD` in [base/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md#cmd) and in [browsers/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md#cmd)
Add a sub-heading `ENTRYPOINT` to [included/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md).
=> docs: add entrypoint info to included README

circle.yml
Multiple job logs from the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow show the warning:
> --progress is a global compose flag, better use `docker compose --progress xx build ...#0 building with "default" instance using docker driver
in response to a Docker CLI command such as:
> docker compose build --progress plain test-factory-cypress-included-electron
Move the `--progress` compose flag in each of the relevant instances in [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) as suggested by the warning. For example, change to:
> docker compose --progress plain build test-factory-cypress-included-electron
=> ci: fix compose --progress plain build cli syntax

factory/test-project/argsDefined.Dockerfile, factory/test-project/docker-compose.yml
The `args-defined` test, defined in [factory/test-project/docker-compose.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/docker-compose.yml), fails because Google Chrome version `107.0.5304.121-1`, released on Nov 24, 2022, is no longer available for download. Google Chrome purges older browser versions.
This test is not executed in CI. It can however be executed manually.
[factory/test-project/argsDefined.Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/argsDefined.Dockerfile) currently uses
https://github.com/cypress-io/cypress-docker-images/blob/99c6a03600e9d78fdef710cad66cecdee51bb9d6/factory/test-project/argsDefined.Dockerfile#L2-L4
- Browser versions defined in …
=> test: bump args-defined browser versions

factory/.env
Updates the factory to cypress 13.13.1 and updates browsers to latest available
=> update factory for cypress 13.13.1

README.md
Currently only the [included/README](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) refers to the `user` parameter to run a Cypress Docker image as container.
Older Docker images fail to run in GitHub Actions if `options: --user 1001` is not applied. Since it is not mandatory to use the Cypress JavaScript GitHub Action, there is a gap in the documentation when a GitHub Actions workflow is used **without** the Cypress JavaScript GitHub Action.
Add information about the `user` parameter information to the main [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) document. Mention the non-root `node` user added to `base`, `browsers` and `included` images.
Include links to Docker documentation.
Add the instruction `options: …
=> docs: add user parameter info to main readme

README.md
The [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) document does not yet link to the document site's [Continuous Integration > Introduction > Setting up CI > CI Docker examples](https://docs.cypress.io/guides/continuous-integration/introduction#CI-Docker-examples) section.
Extend the [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) document to link to the Cypress document site's [Continuous Integration > Introduction > Setting up CI > CI Docker examples](https://docs.cypress.io/guides/continuous-integration/introduction#CI-Docker-examples) section, which itself links to various examples of using Cypress Docker images in CI environments.
=> docs: link into docs CI examples

circle.yml
- closes https://github.com/cypress-io/cypress-docker-images/issues/1095
- Following the successful merge of PR https://github.com/cypress-io/cypress-docker-images/pull/1160, the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow is now using machine image [ubuntu-2204:2024.01.1](https://discuss.circleci.com/t/linux-machine-executor-2024-q1-update/50198) from [Circle CI Machine Images > ubuntu-2204](https://circleci.com/developer/machine/image/ubuntu-2204). The Docker Engine version [24.0.7](https://docs.docker.com/engine/release-notes/24.0/#2407) was however already released 9 months ago in October 2023. The latest CircleCI Ubuntu machine image offers Docker Engine [26.0.2](https://docs.docker.com/engine/release-notes/26.0/#2602).
Update the …
=> chore: update circleci to ubuntu-2204:2024.05.1 (latest) machine image

CONTRIBUTING.md
The document [CONTRIBUTING.md](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md) contains some minor formatting and other text issues:
- Docker terms "Docker Hub" and "Docker" not always written according to their Trademark
- Prettier suggests formatting changes
- Write "Docker Hub" and "Docker" correctly
- Format literal references
- Format according to Prettier rules
- Correct typos & grammar
=> docs: re-format contributing

base/README.md, browsers/README.md, factory/README.md, included/README.md
Prettier recommends whitespace changes for the main README files:
- [base/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md)
- [browsers/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md)
- [included/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md)
- [factory/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md)
Apply the recommended whitespace changes from Prettier for the above README files.
=> docs: minor re-format readme files

package-lock.json, package.json
The repo is currently configured for the older `pretter@2.5.1` release. `prettier@3.0.0` was already released about a year ago, and the current version is `prettier@3.3.3`. Prettier release summaries are posted to their [blog](https://prettier.io/blog/).
Prettier is currently not used in CI, however it is available if needed for format checks / reformatting.
Update prettier from `2.5.1` to [3.3.3](https://github.com/prettier/prettier/releases/tag/3.3.3).
=> chore(deps): update prettier to 3.3.3

examples/basic-mini/index.html, examples/basic/index.html, examples/included-as-non-root/src/index.html
Prettier recommends minor changes for the example html files:
- [examples/basic-mini/index.html](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/basic-mini/index.html)
- [examples/basic/index.html](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/basic/index.html)
- [examples/included-as-non-root/src/index.html](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/included-as-non-root/src/index.html)
- Apply the recommended changes from Prettier for the above `*.html` files.
These are source changes only. The pages displayed in a web browser are unchanged.
=> chore: re-format html sources

.prettierignore
Prettier suggests reformatting the Cypress [factory/test-project](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/test-project). This project is however set up using pre-defined Cypress scaffolding steps (see [README.MD](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/README.MD)) and most files have been through an ESLint formatting check performed in the [cypress-io/cypress-example-kitchensink](https://github.com/cypress-io/cypress-example-kitchensink). Prettier and ESLint do not agree in their preferred formatting.
Add `/factory/test-project` to [.prettierignore](https://github.com/cypress-io/cypress-docker-images/blob/master/.prettierignore) to disable Prettier checking of imported test project files.
=> chore: remove factory/test-project from prettier checks

base-internal/releases/centos-7/Dockerfile, base-internal/releases/centos-7/README.md, base-internal/releases/centos-7/build.sh
to host in dockerhub to build glibc related binaries. We are building a centos7 image to host in dockerhub mainly due to us needing to rebuild better-sqlite3 against an older version of glibc. Since centos7 is EOLed, we need to point the mirrors in the image to the centos vault. Building and storing this image prevents the need to call out to these mirrors and rebuild the image
=> chore: create centos-7 image 

factory/.env
Google released a new major Chrome Desktop version `127` on July 23, 2024:
- [127.0.6533.72-1](https://chromereleases.googleblog.com/2024/07/stable-channel-update-for-desktop_23.html) for Linux 
The Cypress Docker images repo is currently configured for Chrome [126.0.6478.126-1](https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop_24.html), released on June 24, 2024.
https://github.com/cypress-io/cypress-docker-images/blob/ce3385940051f8114b39654da9ddc73051dc1087/factory/.env#L19-L20
Update [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) to
```text
CHROME_VERSION='127.0.6533.72-1'
```
- https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
- https://chromereleases.googleblog.com/
=> chore(deps): update Chrome to 127.0.6533.72-1

factory/.env, factory/CHANGELOG.md
- updates nodes in the docker factory to `20.16.0`
- bumps chrome to version `127.0.6533.88-1`
- bumps edge to  version `127.0.2651.74-1`
- bumps firefox to version `128.0.3`
- installs Cypress version `13.13.2`
=> chore: add cypress 13.13.2 to docker factory and bump shipped browsers

CONTRIBUTING.md, factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1184
The Global Cleanup phase of the `factory` build process defined in [factory/factory.Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/factory.Dockerfile) deletes the Debian system directories:
- `/usr/share/doc`
- `/usr/share/man`
According to https://github.com/cypress-io/cypress-docker-images/issues/1184 the full default empty directory structure of `/usr/share/man` is necessary for installation of the Debian package [default-jre](https://packages.debian.org/bookworm/default-jre).
The `cypress/factory` image is built on [debian:12-slim](https://hub.docker.com/_/debian) which includes a description:
> Image Variants
> `debian:<suite>-slim`
> These tags are an experiment in providing …
=> build: remove factory /usr/share/man deletion

factory/factory.Dockerfile
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1186
Docker Desktop [4.33.0](https://docs.docker.com/desktop/release-notes/#4330) introduced new BuildKit checking:
> BuildKit now evaluates Dockerfile rules to inform you of potential issues.
The check reveals that [factory/factory.Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/factory.Dockerfile) violates the rule `InvalidDefaultArgInFrom` as explained in https://docs.docker.com/reference/build-checks/invalid-default-arg-in-from/
There is no default value for BASE_IMAGE defined.
https://github.com/cypress-io/cypress-docker-images/blob/359c915d01fcd9e64282ae0904d2ce11db3abe87/factory/factory.Dockerfile#L1-L4
Instead, the build process, using `docker compose build factory`, relies on …
=> build: add default BASE_IMAGE to factory.Dockerfile

README.md
A clear overview of browsers is missing in the [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) document.
Add a Browsers section to the [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) document.
Link in issues regarding `arm64` browser additions.
=> docs: add browser section to readme

README.md, examples/firefox-esr/Dockerfile, examples/firefox-esr/README.md, examples/firefox-esr/cypress.config.js, examples/firefox-esr/cypress/e2e/spec.cy.js, examples/firefox-esr/index.html, examples/firefox-esr/package-lock.json, examples/firefox-esr/package.json
The [Mozilla Firefox](https://www.mozilla.org/firefox) browser is currently packaged into Cypress Docker `Linux/amd64` images in the repositories `cypress/browsers` and `cypress/included`, however the corresponding `Linux/arm64` platform images do not include Firefox.
Firefox for `Linux/arm64` is not part of the factory build process and it is not documented how to include it in a custom-built Cypress Docker image.
As can be seen for instance on https://download-installer.cdn.mozilla.net/pub/firefox/releases/129.0.1/, there is no download directory for Linux on ARM64. This is currently the barrier to integrating Firefox `Linux/arm64` into the factory build process.
Mozilla announced [Firefox Nightly Now Available for Linux on ARM64](https://blog.nightly.mozilla.org/2024/04/19/firefox-night …
=> test: add firefox-esr example

factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
- Closes https://github.com/cypress-io/cypress-docker-images/issues/584
[cypress/factory](https://github.com/cypress-io/cypress-docker-images/tree/master/factory), and other Cypress Docker images, built using the `factory` process, do not include [zstd](https://packages.debian.org/stable/utils/zstd) (fast lossless compression algorithm) from [Debian packages](https://www.debian.org/distrib/packages), however they do include [gzip](https://packages.debian.org/stable/utils/gzip) (compress or expand files), which is classed as "essential" and is already part of the `debian:12-slim` image.
For comparison, GitHub Linux runner images, such as [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md), include both …
=> feat(deps): add zstd to factory image

factory/Dockerfile
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1197
Docker Desktop [4.33.0](https://docs.docker.com/desktop/release-notes/#4330) introduced new BuildKit checking:
> BuildKit now evaluates Dockerfile rules to inform you of potential issues.
The check reveals that [factory/Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/Dockerfile) violates the rule `InvalidDefaultArgInFrom` as explained in https://docs.docker.com/reference/build-checks/invalid-default-arg-in-from/
There is no default value for `FACTORY_VERSION` defined.
https://github.com/cypress-io/cypress-docker-images/blob/359c915d01fcd9e64282ae0904d2ce11db3abe87/factory/Dockerfile#L1-L2
Instead, the build process, using for instance `docker compose build base`, relies on …
=> build: add default FACTORY_VERSION to Dockerfile

factory/.env, factory/CHANGELOG.md
updates the default factory node version from `20.16.0` to `20.17.0`
=> chore: update node version of favtory from 20.16.0 to 20.17.0

CONTRIBUTING.md, factory/.env, factory/docker-compose.yml
The contributor documentation refers to publishing "older versions". This is not a good description as it does not cover publishing Cypress Docker images with current Node.js versions later than the active LTS version.
The distinction is now made between "Primary versions" and "Alternate versions" since the alternate versions could be older or newer than the primary versions.
=> docs: change contributor's description from old to alternate versions

factory/.env
Updates the factory to use Cypress 13.14.0, chrome 128, edge 128, and firefox 129.0.2
=> chore: support cypress 13.14.0 and update to chrome 128, edge 128, and firefox 129.0.2

factory/.env
updates cypress to 13.14.2 and updates chrome, edge, and firefox to latest.
=> chore: update cypress to 13.14.2 and update browsers

factory/.env, factory/CHANGELOG.md
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1207
[Debian 12.7](https://www.debian.org/News/2024/20240831) was released on Aug 31, 2024.
Cypress Factory is currently based on [Debian 12.6](https://www.debian.org/News/2024/20240629).
See [Debian Releases](https://www.debian.org/releases/) for an overview.
Update to `BASE_IMAGE='debian:12.7-slim'`
=> feat: update to Debian 12.7 (bookworm)

circle.yml
CircleCI contains a check for a fixed version of `git`, however this version is not under control of the `factory` build process. This causes unplanned workflow failures when new versions of `git` are released.
This is the hard-coded check:
https://github.com/cypress-io/cypress-docker-images/blob/dc421e766155fb3096646cf04108c61d3afb587e/circle.yml#L132-L141
The version of `git` depends on the `BASE_IMAGE`:
https://github.com/cypress-io/cypress-docker-images/blob/dc421e766155fb3096646cf04108c61d3afb587e/factory/.env#L9
and so far this is a Debian image, it depends also on the currently distributed package version according to [Package git](https://packages.debian.org/search?keywords=git) which is picked up by the build process:
https://github.com/cypress-io/cypress-docker-images/blob/dc421e …
=> ci: relax hard-coded version check for git

browsers-internal/releases/node-18/node18.17.1-chrome128-ff130/Dockerfile, browsers-internal/releases/node-18/node18.17.1-chrome128-ff130/README.md, browsers-internal/releases/node-18/node18.17.1-chrome128-ff130/build.sh, browsers-internal/releases/node-18/node18.17.1-chrome128-ff130/global-profile.sh, factory/.env
Additionally updates browsers in docker factory for end users.
NOTE: the internal image `cypress/browsers-internal:node18.17.1-chrome128-ff130` is published manually.
=> chore: add internal 18.17.1 chrome 128 and firefox 130 image and update factory browsers

circle.yml
- PR https://github.com/cypress-io/cypress-docker-images/pull/1163 updated the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow to use machine image `ubuntu-2204:2024.05.1` from [Circle CI Machine Images > ubuntu-2204](https://circleci.com/developer/machine/image/ubuntu-2204).
- The Docker Engine version [26.0.2](https://docs.docker.com/engine/release-notes/26.0/#2602) was released 5 months ago in April 2024. The latest CircleCI Ubuntu machine image `ubuntu-2204:2024.08.1` offers Docker Engine [26.1.4](https://docs.docker.com/engine/release-notes/26.1/#2614) (released in June 2024) according to the CircleCI posting [Ubuntu 20.04, 22.04, 24.04 - Q3 Edge Release](https://discuss.circleci.com/t/ubuntu-20-04-22-04-24-04-q3-edge-release/51699). …
=> chore: update circleci to ubuntu-2204:2024.08.1 (latest) machine image

README.md
The documentation does not describe how to enable Cypress debug logs when running Cypress in a Docker container.
Add a section "Debug logs" to the [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) documentation.
=> docs: add cypress debug instructions

circle.yml
The ssh version output in job `check-factory-versions`, step `check ssh version` in the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow is incorrectly formatted. See for instance https://app.circleci.com/pipelines/github/cypress-io/cypress-docker-images/2263/workflows/a3348dc7-4903-4dc9-807a-01b06f24fe90/jobs/69265/parallel-runs/0/steps/0-112
```text
OpenSSH_9.2p1 Debian-2+deb12u3, OpenSSL 3.0.14 4 Jun 2024
Version  confirmed
```
In the command
```shell
ACTUAL_VERSION=$(docker compose run test-factory-all-included ssh -V)
```
the output of `ssh -V` is sent to `stderr` where it is output directly and not fed into the environment variable `ACTUAL_VERSION`.
In the step `check ssh version` of the job `check-factory-versions` in the workflow …
=> chore: correct ssh version output in circleci

factory/.env
updates cypress to 13.15.0 and updates chrome and edge to latest
=> chore: updates cypress to 13.15.0 and updates chrome and edge to latest

factory/.env, factory/CHANGELOG.md
- relates to https://github.com/cypress-io/cypress-docker-images/issues/1217
Concerning
| Image           | Debian | Published    | Version |
| --------------- | ------ | ------------ | ------- |
| cypress/factory | `12.7` | Sep 10, 2024 | `4.2.0` |
```shell
trivy image --ignore-unfixed --pkg-types os --scanners vuln --severity CRITICAL cypress/factory:latest
```
reports critical fixed issues not yet installed
```text
cypress/factory:latest (debian 12.7)
Total: 5 (CRITICAL: 5)
┌───────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────────┬─────────────────────────────────────────────────────────────┐
│  Library  │ Vulnerability  │ Severity │ Status │ Installed Version │   Fixed Version    │                            Title                            │ …
```
=> fix(deps): rebuild factory with latest debian fixes

factory/.env, factory/CHANGELOG.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/1217
Concerning
| Image            | Debian | Published    | Version                                                               |
| ---------------- | ------ | ------------ | --------------------------------------------------------------------- |
| cypress/base     | `12.6` | Aug 26, 2024 | `20.17.0`                                                             |
| cypress/browsers | `12.7` | Sep 25, 2024 | `node-20.17.0-chrome-129.0.6668.70-1-ff-130.0.1-edge-129.0.2792.52-1` |
| cypress/included | `12.7` | Sep 25, 2024 | `13.15.0`                                                             |
```shell
trivy image --ignore-unfixed --pkg-types os --scanners vuln --severity CRITICAL cypress/base:latest
trivy image …
```
=> fix(deps): update to node.js 20.18.0

base-internal/releases/node-20/20.15.0-buster-python3.8-gcc-10.5/Dockerfile, base-internal/releases/node-20/20.15.0-buster-python3.8-gcc-10.5/README.md, base-internal/releases/node-20/20.15.0-buster-python3.8-gcc-10.5/build.sh
The goal here is to have a buster image that is capable of building better sqlite3. For that we need:
- gcc-10
- g++-10
- python 3.8
We will still use the existing buster image for testing the built binary to ensure that the binary can still work on glibc 2.28.
=> chore: create a 20.15 buster image that can be used for building better sqlite3

factory/.env, factory/CHANGELOG.md, factory/installScripts/node/default.sh
- closes https://github.com/cypress-io/cypress-docker-images/issues/1234
The signature of [Node.js v22.10.0 (current)](https://nodejs.org/en/blog/release/v22.10.0) cannot be checked because it was published by Antoine du Hamel (on Oct 16, 2024) and his new signature from [Node.js release key](https://github.com/nodejs/node/blob/main/README.md#release-keys) is missing from `cypress/factory`.
Add the [Node.js release key](https://github.com/nodejs/node/blob/main/README.md#release-keys) for
> Antoine du Hamel <duhamelantoine1995@gmail.com> `C0D6248439F1D5604AAFFB4021D900FFDB233756`
to [factory/installScripts/node/default.sh](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/installScripts/node/default.sh) and bump the `FACTORY_VERSION` to `4.3.0`
```shell
cd factory …
```
=> feat: add Node.js GPG key for Antoine du Hamel

factory/.env
In the Cypress Docker Factory:
- updates Chrome to `130.0.6723.69-1`
- updates Edge to `130.0.2849.52-1`
- updates Firefox to `131.0.3`
- bumps Cypress to `13.15.1`
=> chore: update factory to browser latest and bump cypress version to 13.15.1

examples/basic/package-lock.json, examples/basic/package.json, examples/chromium/package-lock.json, examples/chromium/package.json, examples/firefox-esr/package-lock.json, examples/firefox-esr/package.json
[examples/basic](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/basic) is configured with `cypress@13.11.0`.
[cypress@13.13.0](https://docs.cypress.io/app/references/changelog#13-13-0) is the minimum version compatible with Firefox `129` and above. Lower versions of Cypress fail to connect to Firefox. Using the pre-configured Cypress project in [examples/basic](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/basic) will therefore fail with current versions of Firefox.
For consistency across examples, update each of the following directories to `cypress@latest` ([cypress@13.15.1](https://docs.cypress.io/app/references/changelog#13-15-1)):
- [examples/basic](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/basic)
- …
=> test: update cypress in examples to 13.15.1

factory/.env, factory/CHANGELOG.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/1239
Today, Oct 29, 2024 Node.js `22.x` transitioned from Current status into Active Long Term Support (LTS) status with the release of [Node.js 22.11.0](https://nodejs.org/en/blog/release/v22.11.0), codename 'Jod'.
Node.js `20.x` previously transitioned from Active LTS to Maintenance LTS status on Oct 22, 2024 (see [Node.js release schedule](https://github.com/nodejs/release#release-schedule)).
[factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) currently calls out `FACTORY_DEFAULT_NODE_VERSION='20.18.0'` referring to what is now a Node.js Maintenance LTS version.
In [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) bump the following …
=> feat(deps): update to active lts node.js 22.11.0

.github/workflows/example-cypress-github-action.yml
The example workflow [.github/workflows/example-cypress-github-action.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/.github/workflows/example-cypress-github-action.yml) runs jobs in the GitHub-hosted runner [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md).
Ubuntu `24.04.1` LTS (Noble Numbat) is the latest [Ubuntu release](https://wiki.ubuntu.com/Releases) in the Long Term Support (LTS) category and is available as a GitHub-hosted runner [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md).
Update the example workflow [.github/workflows/example-cypress-github-action.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/.github/workflows/example-cypress- …
=> test: update github-actions example to ubuntu-24.04 runner

CONTRIBUTING.md
When running test steps defined in [CONTRIBUTING > Building locally](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#building-locally), the command
```shell
docker compose run --rm test-factory-all-included
```
will use an image `test-project-test-factory-all-included`, if it exists from previous tests, to run new tests. This ignores parameters in [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) and so any changed parameters are not tested in this case, leading to unexpected results.
In [CONTRIBUTING > Building locally](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#building-locally) add the `--build` option to `docker compose run`, so the command becomes:
```shell
docker compose …
```
=> docs: correct contributing test steps

included/README.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/1109
- closes https://github.com/cypress-io/cypress-docker-images/issues/1119
- closes https://github.com/cypress-io/cypress-docker-images/issues/1222
The [included/README](https://github.com/cypress-io/cypress-docker-images/blob/master/included/README.md) is extended regarding usage of the Cypress Docker image `cypress/included`
1. The examples are aligned with the [base/README](https://github.com/cypress-io/cypress-docker-images/blob/master/base/README.md) and [browsers/README](https://github.com/cypress-io/cypress-docker-images/blob/master/browsers/README.md) documents.
2. A section "Continuous Integration" is added, with sub-sections
- GitHub Actions
- GitLab Pipelines
3. A missing `cypress-` string is added to the …
=> docs: extend included examples

factory/.env
updates Cypress to `13.15.2`
updates Chrome to `130.0.6723.116-1`
updates Edge to `130.0.2849.68-1`
updates Firefox to `132.0.1`
=> chore: Cypress 13.15.2 release

factory/.env, factory/CHANGELOG.md
feat: update to Debian 12.8 (bookworm)
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1252
[Debian 12.8](https://www.debian.org/News/2024/20241109) was released on Nov 9, 2024.
Cypress Factory is currently based on [Debian 12.7](https://www.debian.org/News/2024/20240831)
See [Debian Releases](https://www.debian.org/releases/) for an overview.
Update to `BASE_IMAGE='debian:12.8-slim'`
Also fixed a missing bracket in the previous [CHANGELOG](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/CHANGELOG.md) entry.
=> feat: update to Debian 12.8 (bookworm)

base/README.md, browsers/README.md, examples/chromium/README.md, examples/firefox-esr/README.md
Some examples are using `/e2e` as a generic working directory in a Docker command line. For example:
```shell
docker run -it --rm -v .:/e2e -w /e2e cypress/base
```
This is a carry-over from legacy Cypress when only End-to-End tests were supported.
It is a misleading naming usage which suggests this is about E2E only. Cypress Docker images can however be used to execute both End-to-End and Component Testing.
The directory name in the Docker options `-v` and `-w` is arbitrary and changed from `/e2e` to a neutral name `/app`.
=> docs: use /app as standard example working directory

circle.yml
- PR #1202 changed the usage of the terms "new" and "older" versions in the [CONTRIBUTING](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md) document to refer instead to "primary" and "alternate" versions, since especially alternate Node.js versions could be older or newer than primary active LTS versions.
- Comments in [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) however still refer to older / old versions.
In [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) change code comments to use the terms "primary" and "alternate" versions.
=> chore: change circleci comments from old to alternate versions

circle.yml
- PR https://github.com/cypress-io/cypress-docker-images/pull/1214 updated the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow to use machine image `ubuntu-2204:2024.08.1` from [Circle CI Machine Images > ubuntu-2204](https://circleci.com/developer/machine/image/ubuntu-2204).
- The Docker Engine version [26.1.4](https://docs.docker.com/engine/release-notes/26.1/#2614) was released 5 months ago in June 2024. The latest CircleCI Ubuntu machine image `ubuntu-2204:2024.11.1`, as shown on the [CircleCI machine image overview](https://circleci.com/developer/images?imageType=machine), offers Docker Engine [27.3.1](https://docs.docker.com/engine/release-notes/27/#2731) (released in Sept 2024).
Update the …
=> chore: update circleci to ubuntu-2204:2024.11.1 (latest) machine image

base-internal/releases/node-20/20.18.1-bullseye/Dockerfile, base-internal/releases/node-20/20.18.1-bullseye/README.md, base-internal/releases/node-20/20.18.1-bullseye/build.sh, base-internal/releases/node-20/20.18.1-yarn-berry/Dockerfile, base-internal/releases/node-20/20.18.1-yarn-berry/README.md, base-internal/releases/node-20/20.18.1-yarn-berry/build.sh, base-internal/releases/node-20/20.18.1/Dockerfile, base-internal/releases/node-20/20.18.1/README.md, base-internal/releases/node-20/20.18.1/build.sh, browsers-internal/releases/node-20/node20.18.1-bullseye-chrome131-ff133/Dockerfile, browsers-internal/releases/node-20/node20.18.1-bullseye-chrome131-ff133/README.md, browsers-internal/releases/node-20/node20.18.1-bullseye-chrome131-ff133/build.sh, browsers-internal/releases/node-20/node20.18.1-bullseye-chrome131-ff133/global-profile.sh, browsers-internal/releases/node-20/node20.18.1-chrome131-ff133/Dockerfile, browsers-internal/releases/node-20/node20.18.1-chrome131-ff133/README.md, browsers-internal/releases/node-20/node20.18.1-chrome131-ff133/build.sh, browsers-internal/releases/node-20/node20.18.1-chrome131-ff133/global-profile.sh
Added:
- `cypress/base-internal:20.18.1-bullseye`
- `cypress/base-internal:20.18.1-yarn-berry`
- `cypress/base-internal:20.18.1`
- `cypress/browsers-internal:node20.18.1-bullseye-chrome131-ff133`
- `cypress/browsers-internal:node20.18.1-chrome131-ff133`
=> adding internal node 20.18.1 docker images

factory/.env
updates Cypress to 13.17.0
updates Chrome to 131.0.6778.139-1
updates Edge to 131.0.2903.99-1
updates Firefox to 133.0.3
=> chore: Cypress 13.17.0 release

examples/basic/package-lock.json, examples/basic/package.json, examples/chromium/package-lock.json, examples/chromium/package.json, examples/firefox-esr/package-lock.json, examples/firefox-esr/package.json
Examples configured with `cypress@13.15.1` and earlier display `[DEP0040] DeprecationWarning: The punycode module is deprecated.` when run against `latest` Cypress Docker images which now use the Active LTS version Node.js 22.
Update all examples in the [examples](https://github.com/cypress-io/cypress-docker-images/tree/master/examples) sub-directories to use `cypress@13.17.0`.
=> chore(deps): update cypress to 13.17.0 in examples

.github/workflows/example-tests.yml, examples/basic-mini/scripts/test.sh, examples/basic/scripts/test.sh, examples/chromium/scripts/test.sh, examples/firefox-esr/scripts/test.sh, examples/included-as-non-root/scripts/test.sh, examples/test-all-examples.sh
There is no automated testing available for the set of examples in the [examples directory](https://github.com/cypress-io/cypress-docker-images/tree/master/examples).
- Add a test script `scripts/test.sh` for each of the sub-directories of the [examples directory](https://github.com/cypress-io/cypress-docker-images/tree/master/examples)
- Add a `examples/test-all-examples.sh` script to run all the above scripts
- Add a GitHub Actions workflow to run each of the individual test scripts
On Ubuntu `24.04.1` LTS, Node.js `22.12.0` LTS with Docker Desktop `4.37.1`
```shell
git clone https://github.com/cypress-io/cypress-docker-images
cd cypress-docker-images
cd examples
./test-all-examples.sh
```
Under https://github.com/cypress-io/cypress-docker-images/actions run workflow
"Example Tests"
=> test: add tests for examples

examples/included-as-non-root/README.md, examples/included-as-non-root/cypress.config.js, examples/included-as-non-root/cypress/e2e/spec.cy.js
[examples/included-as-non-root](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/included-as-non-root) cannot capture screenshots when running with a non-root user in GitHub Actions.
In [actions/workflows/example-tests.yml](https://github.com/cypress-io/cypress-docker-images/actions/workflows/example-tests.yml) running the job `example (included-as-non-root)` in GitHub Actions, Cypress outputs the warning:
```text
This folder is not writable: /test
Writing to this directory is required by Cypress in order to store screenshots and videos.
Enable write permissions to this directory to ensure screenshots and videos are stored.
If you don't require screenshots or videos to be stored you can safely ignore this warning.
```
See logs in …
=> test: set up included-non-root example screenshot

README.md
- partially resolves issue #1272
- possibly also related to issue https://github.com/cypress-io/cypress-docker-images/issues/914
If a custom Docker image is built from `cypress/base` or `cypress/browsers` and a Cypress binary is installed (for instance with `npx cypress install`) and the custom image is then run with a non-root user, Cypress will fail to run with an error message:
> Error: EACCES: permission denied, open '/root/.cache/Cypress/`<Cypress version>`/binary_state.json'
This is due to an open Cypress issue https://github.com/cypress-io/cypress/issues/30684 where Cypress fails to verify the installed Cypress binary if it does not have write access to the Cypress binary directory.
Follow the steps in [cypress/base README > Docker build and …
=> docs: add binary_state.json permission denied known problem

README.md, examples/included-as-non-root/README.md
- closes #1275
If a Cypress Docker image is run with a non-root user other than the configured `node` (`1000`) user, and if no additional measures are taken, multiple subsystems which rely on being able write into the Linux $HOME directory are unable to cache intermediate results. This causes Cypress to fail to run. The error message contains the text:
```text
Fontconfig error: No writable cache directories
The Test Runner unexpectedly exited via a exit event with signal SIGTRAP
```
Cypress Docker images (`cypress/base`, `cypress/browsers`, `cypress/included` & custom images generated from `cypress/factory`) include only a `home` directory for the non-root user `node` (`1000`). This directory is owned by the user `node` and does not allow other users write access.
Executing `npx cypress …
=> docs: add mitigation instructions non-root user not node

factory/.env
Updates the factory browsers to latest and Cypress to v14.
=> chore: update factory browsers to latest and update to Cypress 14

factory/.env, factory/CHANGELOG.md
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1282
[Debian 12.9](https://www.debian.org/News/2025/20250111) was released on Jan 11, 2025.
Cypress Factory is currently based on [Debian 12.8](https://www.debian.org/News/2024/20241109)
See [Debian Releases](https://www.debian.org/releases/) for an overview.
Update to `BASE_IMAGE='debian:12.9-slim'`
Update to `FACTORY_VERSION='5.2.0'`
=> feat: update to Debian 12.9 (bookworm)

factory/.env, factory/CHANGELOG.md
- The Node.js project released a security update [Node.js v22.13.1 LTS](https://nodejs.org/en/blog/release/v22.13.1) on Jan 21, 2025.
| Environment variable           | Before             | After              |
| ------------------------------ | ------------------ | ------------------ |
| `FACTORY_VERSION`              | `5.2.0`            | `5.2.1`            |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.13.0`          | `22.13.1`          |
| `CHROME_VERSION`               | `132.0.6834.83-1`  | no change          |
| `EDGE_VERSION`                 | `131.0.2903.147-1` | `132.0.2957.115-1` |
| `FIREFOX_VERSION`              | `134.0.1`          | `134.0.2`          |
=> fix(deps): update to Node.js 22.13.1

examples/basic/package-lock.json, examples/basic/package.json, examples/chrome-for-testing/package-lock.json, examples/chrome-for-testing/package.json, examples/chromium/package-lock.json, examples/chromium/package.json, examples/firefox-esr/package-lock.json, examples/firefox-esr/package.json
The [examples](https://github.com/cypress-io/cypress-docker-images/tree/master/examples) are updated to [cypress@14.0.0](https://docs.cypress.io/app/references/changelog#14-0-0) (current `latest`).
=> chore(deps): update cypress to 14.0.0 in examples

factory/test-project/cypress/support/e2e.js
- The scaffolded contents of [factory/test-project/cypress/support/e2e.js](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/test-project/cypress/support/e2e.js) in the [factory/test-project](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/test-project) are no longer exactly aligned with Cypress >= `13.17.0` due to PR https://github.com/cypress-io/cypress/pull/30738.
- Cypress has removed the comment text from the default scaffolded file `support/e2e.js`:
> // Alternatively you can use CommonJS syntax:
> // require('./commands')
- Recreate [factory/test-project/cypress](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/test-project/cypress) using Cypress `14.0.0`.
This is a housekeeping chore with only a change in comment …
=> chore: update test-project cypress/support/e2e.js to cypress 14.0.0

.github/workflows/example-tests.yml, examples/basic-mini/scripts/test.sh, examples/basic/scripts/test.sh, examples/chrome-for-testing/scripts/test.sh, examples/chromium/scripts/test.sh, examples/firefox-esr/scripts/test.sh, examples/included-as-non-root/scripts/test.sh, examples/test-all-examples.sh
- closes https://github.com/cypress-io/cypress-docker-images/issues/1290
Examples in the [examples](https://github.com/cypress-io/cypress-docker-images/tree/master/examples) directory are currently tested in GitHub Actions through the workflow [.github/workflows/example-tests.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/.github/workflows/example-tests.yml) tests using the GitHub Actions runner image [ubuntu-24.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md), which runs on a `Linux/amd64` platform.
Examples are not tested on a `Linux/arm64` platform.
- Add the GitHub Actions runner image `ubuntu-24.04-arm` to the workflow [.github/workflows/example-tests.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/.g …
=> test: run examples in Ubuntu arm64 on GitHub

base-internal/releases/node-20/20.18.1-bullseye/Dockerfile
updates the base internal `cypress/base-internal:20.18.1-bullseye` image to include dependencies that are needed to run firefox and chrome.
Cypress is going to no longer use the `browsers-internal` images in https://github.com/cypress-io/cypress/pull/30943, so this image is used as the new base with the browser-tools circle orb
=> chore: update internal docker image

factory/.env, factory/CHANGELOG.md, factory/installScripts/firefox/default.sh, factory/installScripts/firefox/install-firefox-version.js
- closes https://github.com/cypress-io/cypress-docker-images/issues/1294
[Firefox 135.0](https://www.mozilla.org/en-US/firefox/135.0/releasenotes/) announced that "Linux binaries are [now provided in XZ format](https://blog.nightly.mozilla.org/2024/11/28/announcing-faster-lighter-firefox-downloads-for-linux-with-tar-xz-packaging/), replacing the previous BZ2 format, offering faster unpacking and smaller file sizes."
The change is not compatible with the current [factory/installScripts/firefox/default.sh](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/installScripts/firefox/default.sh) which assumes a `bz2` extension for the Firefox download file. Attempting to configure Firefox `135.0` therefore fails.
For Firefox `134` and below use `bz2` with `tar -xjf`
For …
=> feat: support firefox 135 and above with xz compression

factory/.env
Updates Cypress to `14.0.2` and updates the browsers to latest stable versions
=> chore: cypress 14.0.2 release and bump browser versions

factory/.env, factory/CHANGELOG.md
- The Node.js project released an update [Node.js v22.14.0 LTS](https://nodejs.org/en/blog/release/v22.14.0) on Feb 11, 2025.
| Environment variable           | Before             | After             |
| ------------------------------ | ------------------ | ----------------- |
| `FACTORY_VERSION`              | `5.3.0`            | `5.3.1`           |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.13.1`          | `22.14.0`         |
| `CHROME_VERSION`               | `133.0.6943.53-1`  | no change         |
| `EDGE_VERSION`                 | `132.0.2957.140-1` | `133.0.3065.59-1` |
| `FIREFOX_VERSION`              | `135.0`            | no change         |
=> fix(deps): update to Node.js 22.14.0

factory/.env
=> chore: update to Cypress 14.0.3

README.md
The link `Tag Selection` in the [README > Firefox not found](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#firefox-not-found) section has become stale.
The target bookmark was changed to [#tags](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#tags) as part of an update to that section.
Correct the [README > Firefox not found](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#firefox-not-found) link to the[Tags](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#tags) section on the same page.
```shell
npm ci
npx markdown-link-check README.md
```
Ensure that no link errors are reported.
=> docs: correct dead README Tags link

base-internal/releases/node-20/20.18.3-bullseye/Dockerfile, base-internal/releases/node-20/20.18.3-bullseye/README.md, base-internal/releases/node-20/20.18.3-bullseye/build.sh, base-internal/releases/node-20/20.18.3-yarn-berry/Dockerfile, base-internal/releases/node-20/20.18.3-yarn-berry/README.md, base-internal/releases/node-20/20.18.3-yarn-berry/build.sh, base-internal/releases/node-20/20.18.3/Dockerfile, base-internal/releases/node-20/20.18.3/README.md, base-internal/releases/node-20/20.18.3/build.sh
Necessary for Electron 34 latest version: https://github.com/cypress-io/cypress/pull/31260
=> chore: add node 20.18.3 images to base-internal

factory/.env
Updates:
Firefox from 135 to 136
Chrome from 133 to 134
Edge from 133 to 134
Cypress from 14.1.0 to 14.2.0
=> chore: update browsers and bump cypress to 14.2.0 inside the factory

circle.yml, factory/.env, factory/CHANGELOG.md, factory/installScripts/firefox/default.sh, factory/installScripts/firefox/install-firefox-version.js
- closes https://github.com/cypress-io/cypress-docker-images/issues/1306
- Until now, Cypress Docker images only had access to x86 versions of Firefox. The [examples/firefox-esr](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/firefox-esr) additionally demonstrated how to build Firefox from the ESR (Extended Support Release) channel into a custom Cypress Docker image.
- With the release of [Firefox 136.0](https://www.mozilla.org/en-US/firefox/136.0/releasenotes/), Mozilla announced:
> On Linux, Firefox is now available on ARM64 (AArch64), with installation options via APT and tarballs. Flatpak support is coming soon.
- [factory/installScripts/firefox](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/installScripts/firefox) skips installation …
=> feat: enable firefox arm64 build with cypress/factory

factory/CHANGELOG.md
Executing `npm run check:markdown` fails in [factory/CHANGELOG.md](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/CHANGELOG.md) with
> [✖] https://hub.docker.com/repository/docker/cypress/factory/general#
Correct the link in [factory/CHANGELOG.md](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/CHANGELOG.md)
from
`https://hub.docker.com/repository/docker/cypress/factory/general#` (which requires sign in to access)
to
https://hub.docker.com/r/cypress/factory (which requires no sign in)
Execute
```shell
npm run check:markdown
```
and confirm no link errors are reported.
=> docs: fix CHANGELOG link to Docker Hub cypress/factory

circle.yml, factory/.env, factory/CHANGELOG.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/1316
https://github.com/cypress-io/cypress-docker-images/blob/8ebc9b0cbce51656902955b1b70892c52fee4418/circle.yml#L228-L235
pins the publication process to using the historical manifest format:
```json
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
```
- Refer to #1316 for further background information
Move from the historical manifest format to use the default OCI manifest.
- Remove [BUILDX_NO_DEFAULT_ATTESTATIONS=1](https://docs.docker.com/build/building/variables/#buildx_no_default_attestations) from the [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) workflow to allow [Provenance …
=> build: migrate to oci manifest

factory/.env, factory/CHANGELOG.md, factory/README.md, factory/installScripts/yarn/install-yarn-version.js
- relates to https://github.com/cypress-io/cypress-docker-images/issues/882
- closes https://github.com/cypress-io/cypress-docker-images/issues/1317
If `YARN_VERSION` is set to Yarn version >=2, corresponding to Yarn Modern, Cypress factory outputs a 404 message.
Yarn Modern is not published to the npm registry, like Yarn v1 Classic is, explaining the 404 error.
Yarn Modern prefers being [installed](https://yarnpkg.com/getting-started/install) with [Corepack](https://yarnpkg.com/corepack) which however remains in [experimental status](https://nodejs.org/docs/latest/api/corepack.html) and is not recommended for production use.
In [factory/installScripts/yarn/install-yarn-version.js](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/installScripts/yarn/install-yarn-vers …
=> build: add factory Yarn Modern (version >=2) unsupported message

CONTRIBUTING.md, README.md, browsers/README.md, included/README.md
Follows on from:
- https://github.com/cypress-io/cypress-docker-images/issues/1190
- https://github.com/cypress-io/cypress-docker-images/pull/1307
- https://github.com/cypress-io/cypress-docker-images/pull/1307 added:
- the ability for `cypress/factory` to generate Docker images including Firefox `arm64`
- https://github.com/cypress-io/cypress-docker-images/pull/1318 added:
- Firefox `136.0.2` published as part of `Linux/arm64` images
The above is not yet reflected in README documentation.
Add information to READMEs to cover the added support and availability of Firefox for `Linux/arm64` in release `136.0` and above.
=> docs: introduce Firefox arm64 build

.github/workflows/example-tests.yml, examples/basic-mini/scripts/test.sh, examples/basic/scripts/test.sh
- [.github/workflows/example-tests.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/.github/workflows/example-tests.yml) is disabled for the public beta runner image `ubuntu-24.04-arm` from https://github.com/actions/partner-runner-images. The Ubuntu arm64 runner image has however now stabilized.
| Browser                                | `arm64`     | Test state |
| -------------------------------------- | ----------- | ---------- |
| Chrome for Testing                     | unavailable | -          |
| Chromium                               | available   | tested     |
| Firefox Rapid Release (RR)             | available   | untested   |
| Firefox Extended Support Release (ESR) | available   | tested     |
- …
=> test: add firefox arm64 examples tests for gha

factory/.env, factory/CHANGELOG.md
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1324
[Debian 12.10](https://www.debian.org/News/2025/20250315) was released on Mar 15, 2025.
Cypress Factory is currently based on [Debian 12.9](https://www.debian.org/News/2025/20250111).
See [Debian Releases](https://www.debian.org/releases/) for an overview.
Update to `BASE_IMAGE='debian:12.10-slim'`
Update to `FACTORY_VERSION='5.8.0'`
=> feat: update to Debian 12.10 (bookworm)

.prettierignore, circle.yml, eslint.config.mjs, examples/included-as-non-root/cypress.config.js, factory/installScripts/chrome/install-chrome-version.js, factory/installScripts/cypress/install-cypress-version.js, factory/installScripts/edge/install-edge-version.js, factory/installScripts/firefox/install-firefox-version.js, factory/installScripts/webkit/install-webkit-version.js, factory/installScripts/yarn/install-yarn-version.js, package-lock.json, package.json
- Add ESLint modules
- [@stylistic/eslint-plugin@4.2.0](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v4.2.0)
- [eslint@9.22.0](https://github.com/eslint/eslint/releases/tag/v9.22.0)
- [eslint-plugin-cypress@4.2.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v4.2.0)
- [globals@16.0.0](https://github.com/sindresorhus/globals)
- Add script `lint` to [package.json](https://github.com/cypress-io/cypress-docker-images/blob/master/package.json)
- Add job `lint` to [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml)
- Lint and correct all JavaScript files
- Exclude `*.js` files from formating with Prettier to avoid overlap with [@stylistic/eslint-plugin](https://www.npmjs.com/package/@stylistic/eslint-plugin)
Execute …
=> chore: add eslint linting for JavaScript

factory/.env
bumps browsers and Cypress to latest
=> chore: bump browser versions and cypress to latest

.prettierrc, circle.yml, factory/docker-compose.yml
Executing `npm run format` shows multiple suggested changes, including for `*.yml` workflows:
- [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml) is formatted mostly with a 4 character indent, however this has not been consistently applied
- [factory/docker-compose.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/docker-compose.yml) is formatted with a 2 character indent, with some exceptions
The general Cypress development standard indent is 2 characters, as defined in https://github.com/cypress-io/cypress/blob/b60ac5ee7b84f44a435e304b5d4463a02eabb800/npm/eslint-plugin-dev/lib/index.js#L49-L58
```json
'indent': [
'error',
2,
{
// TODO: fix this, we shouldn't need to ignore TemplateLiterals
'ignoredNodes': …
```
=> build: reformat yml workflows according to Prettier

circle.yml, package-lock.json, package.json
- The version of Prettier [prettier@3.3.3](https://github.com/prettier/prettier/releases/tag/3.3.3) used is not the latest.
- Prettier is now able to run without error in the repo.
- Prettier is not checked in CI.
- Update to [prettier@3.5.3](https://github.com/prettier/prettier/releases/tag/3.5.3)
- Add script `format:check` to [package.json](https://github.com/cypress-io/cypress-docker-images/blob/master/package.json) equivalent to:
```shell
npx prettier --check .
```
- Execute script `format:check` in `lint` job of [circle.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/circle.yml)
Execute
```shell
npm run format:check
```
and confirm output is:
> Checking formatting...
> All matched files use Prettier code style!
=> ci: add prettier to circleci linting

factory/.env
updates cypress to `14.3.0` and chrome/edge from 134 to 135 and firefox from 136 to 137
=> chore: update browsers and cypress to latest

README.md
The [Cypress 14.0.0 changelog](https://docs.cypress.io/app/references/changelog#14-0-0) includes the text:
> Cypress now only officially supports the latest 3 major versions of Chrome, Firefox, and Edge - older browser versions may still work, but we recommend keeping your browsers up to date to ensure compatibility with Cypress.
This is not reflected in the Cypress Docker image documentation.
Add a corresponding statement to the [README > Browsers](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#browsers) section.
Link to https://docs.cypress.io/app/references/launching-browsers#Browser-versions-supported
> Cypress officially supports the latest 3 major versions of Chrome, Firefox, and Edge. We recommend using up to date Cypress Docker images for supportability.
=> docs: add 3 major browser versions supportability

factory/.env
updates browsers to latest and Cypress to 14.3.1
=> chore: update browsers to latest and cypress to 14.3.1

base-internal/releases/ubuntu/ubuntu22-node20/Dockerfile, base-internal/releases/ubuntu/ubuntu22-node20/README.md, base-internal/releases/ubuntu/ubuntu22-node20/build.sh, base-internal/releases/ubuntu/ubuntu24-node20/Dockerfile, base-internal/releases/ubuntu/ubuntu24-node20/README.md, base-internal/releases/ubuntu/ubuntu24-node20/build.sh
adds ubuntu 22 and ubuntu 24 images based off of node 20 as node 20 will be the lowest supported node in Cypress 15
=> chore: add ubuntu22 and 24 node 20 images

factory/.env
updates factory to cypress `14.3.2` and updates Chrome to latest
=> chore: update factory to use cypress 14.3.2 and update chrome to latest

factory/.env, factory/CHANGELOG.md
- The Node.js project released an update [Node.js v22.15.0 LTS](https://nodejs.org/en/blog/release/v22.15.0) on Apr 23, 2025.
| Environment variable           | Before             | After     |
| ------------------------------ | ------------------ | --------- |
| `FACTORY_VERSION`              | `5.8.0`            | `5.8.1`   |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.14.0`          | `22.15.0` |
=> fix(deps): update to Node.js 22.15.0

factory/.env
updates browsers to latest and cypress to version `14.3.3`
=> chore: cypress app release 14.3.3

circle.yml, factory/.env, factory/docker-compose.yml
- closes https://github.com/cypress-io/cypress-docker-images/issues/1336
[Node.js 24.0.0](https://nodejs.org/en/blog/release/v24.0.0) was released as a new current version on May 6, 2025. The Node.js 24 release line is planned to be [promoted to LTS status](https://github.com/nodejs/release#release-schedule) on Oct 28, 2025. Cypress should provide Docker images based on the Node.js 24 release line to enable internal and external testing in advance of the change of status to LTS.
Using the feature branch
[14.3.3-node-24.0.0-publish](https://github.com/cypress-io/cypress-docker-images/tree/14.3.3-node-24.0.0-publish)
and following the process described in [Alternate versions](https://github.com/cypress-io/cypress-docker-images/blob/master/CONTRIBUTING.md#alternate-versions), generate and …
=> chore: release images for Node.js 24.0.0

examples/chrome-for-testing/scripts/test.sh
The script [master/examples/chrome-for-testing/scripts/test.sh](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/chrome-for-testing/scripts/test.sh) tests "Chrome for Testing" using versions:
```text
'stable'
'beta'
'dev'
'canary'
'130'
'131.0.6778.204'
```
In the meantime, Cypress supports latest 3 browser versions. The current Chrome version is 136, meaning that the numerical versions used in the test are now unsupported.
The alias `stable` is always supported by Cypress. The other aliases `beta`, `dev` and `canary` give advance access to functionality that is planned to flow into a stable supported release.
Update the numerical versions tested through [master/examples/chrome-for-testing/scripts/test.sh](https://github.com/cypress-io/cypress-docker-images/blob/mas …
=> test: update chrome for testing example versions to 136.x

factory/.env, factory/CHANGELOG.md
- Node.js issued a security release [Node.js v22.15.1 LTS](https://nodejs.org/en/blog/release/v22.15.1) on May 14, 2025.
| Environment variable           | Before            | After              |
| ------------------------------ | ----------------- | ------------------ |
| `FACTORY_VERSION`              | `5.8.1`           | `5.8.2`            |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.15.0`         | `22.15.1`          |
| `CHROME_VERSION`               | `136.0.7103.92-1` | `136.0.7103.113-1` |
| `EDGE_VERSION`                 | `136.0.3240.50-1` | `136.0.3240.64-1`  |
| `FIREFOX_VERSION`              | `138.0.1`         | `138.0.3`          |
=> fix(deps): update to Node.js 22.15.1

factory/.env, factory/CHANGELOG.md
This PR adds the missing bump to Node.js `22.15.1` which PR https://github.com/cypress-io/cypress-docker-images/pull/1349 was supposed to have included.
- Node.js issued a security release [Node.js v22.15.1 LTS](https://nodejs.org/en/blog/release/v22.15.1) on May 14, 2025.
| Environment variable           | Before             | After     |
| ------------------------------ | ------------------ | --------- |
| `FACTORY_VERSION`              | `5.8.2`            | `5.8.3`   |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.15.0`          | `22.15.1` |
| `CHROME_VERSION`               | `136.0.7103.113-1` | unchanged |
| `EDGE_VERSION`                 | `136.0.3240.64-1`  | …
=> fix(deps): update to Node.js 22.15.1 (Rev 2)

README.md
The [README > Known problems > Firefox not found](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#firefox-not-found) description applies to Firefox < `138`, not to the current Firefox 138 version.
Instead of Cypress not finding Firefox, it **does** find Firefox `138.x` and then hangs when attempting to test.
The resolution is the same as when Firefox is not found for previous Firefox versions: the user `1001` must be specified.
Modify [README > Known problems > Firefox not found](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md#firefox-not-found)
- Make it clear that the issue applies only to Firefox < `138`.
- The workflow parameter `options: --user 1001` is correct for all versions.
- Remove the link to …
=> Update Firefox not found in GitHub Actions for Firefox 138

factory/.env
updates cypress to `14.4.0` and updates browsers to latest
=> chore: add cypress 14.4.0 and update browsers to latest

factory/.env, factory/CHANGELOG.md
- Node.js released an update [Node.js v22.16.0 LTS](https://nodejs.org/en/blog/release/v22.16.0) on May 21, 2025.
| Environment variable           | Before             | After             |
| ------------------------------ | ------------------ | ----------------- |
| `FACTORY_VERSION`              | `5.8.3`            | `5.8.4`           |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.15.1`          | `22.16.0`         |
No change to browser versions.
=> fix(deps): update to Node.js 22.16.0

CONTRIBUTING.md, circle.yml, examples/basic-mini/Dockerfile.factory, examples/basic/Dockerfile.factory, examples/firefox-esr/Dockerfile.factory, factory/.env, factory/CHANGELOG.md, factory/README.md, factory/docker-compose.yml, factory/factory.Dockerfile, factory/installScripts/firefox/default.sh, factory/installScripts/firefox/install-firefox-version.js, factory/installScripts/geckodriver/default.sh, factory/installScripts/geckodriver/install-geckodriver-version.js, factory/test-project/docker-compose.yml
- closes https://github.com/cypress-io/cypress-docker-images/issues/1351
The [mozilla/geckodriver](https://github.com/mozilla/geckodriver) is required to test Firefox. It is not part of the Firefox distribution, nor is it included in Cypress. If the driver is unavailable, then testing against Firefox fails. This is typically the case in an air-gapped environment.
If an attempt is made to run Cypress against a Firefox browser in a Cypress Docker container using `cypress/browsers` or `cypress/included` images, Cypress tries to download [mozilla/geckodriver](https://github.com/mozilla/geckodriver). In an air-gapped environment (no Internet access) the download fails and it is not possible to test against Firefox. The same applies to any Docker images built for Firefox with the current …
=> feat: add geckodriver to factory process

README.md, circle.yml, factory/.env, factory/docker-compose.yml, factory/test-project/docker-compose.yml
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1354
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1348
`cypress/browsers` and `cypress/included` images do not include the [Mozilla geckodriver](https://github.com/mozilla/geckodriver) that is required for Firefox testing.
- Update `FIREFOX_VERSION` to `139.0.1` in [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env)
- Add [Mozilla geckodriver](https://github.com/mozilla/geckodriver) to  `cypress/browsers` and `cypress/included` by using the build parameter `GECKODRIVER_VERSION` in [factory/docker-compose.yml](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/docker-compose.yml) and in …
=> feat: add geckodriver to cypress/browsers and cypress/included

README.md
As noted in the Cypress documentation:
- [cypress@14.4.0 changelog](https://docs.cypress.io/app/references/changelog#14-4-0)
- [API > Node Events > before:browser:launch > Add browser extensions](https://docs.cypress.io/api/node-events/browser-launch-api#Add-browser-extensions)
> - Chrome-branded browsers (e.g., standard Chrome) version 137 and above no longer support extension loading via this API, due to the removal of the `--load-extension` flag by Chrome. We recommend using Chrome for Testing or Chromium instead. See Cypress Docker image examples for [Chrome for Testing](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/chrome-for-testing) and [Chromium](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/chromium).
In the Cypress Docker …
=> docs: add Chrome for Testing to main README

examples/chrome-for-testing/Dockerfile
In the [examples/chrome-for-testing > README](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/chrome-for-testing/README.md) [Google Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) is installed using [@puppeteer/browsers](https://www.npmjs.com/package/@puppeteer/browsers)
The instructions to install system dependencies using the following from the README for [@puppeteer/browsers](https://www.npmjs.com/package/@puppeteer/browsers) was not used, because it did not work:
```shell
npx puppeteer browsers install chrome --install-deps
```
Although the example runs without checking for all dependencies, there may be some edge cases that need the complete set of dependencies installed.
In …
=> fix: add chrome for testing dependencies to example

examples/chrome-for-testing/README.md
In the [examples/chrome-for-testing > README](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/chrome-for-testing/README.md) [Google Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) is installed using [@puppeteer/browsers](https://www.npmjs.com/package/@puppeteer/browsers)
- https://github.com/cypress-io/cypress-docker-images/pull/1368 updated the [examples/chrome-for-testing/Dockerfile](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/chrome-for-testing/Dockerfile) to use the installed contents of `/opt/chrome-for-testing/deb.deps` to install any missing dependencies.
This change was not added to the [examples/chrome-for-testing > README](https://github.com/cypress-io/cypress-docker-images/blob/master/examples/chrom …
=> docs: add chrome for testing dependencies to example readme

README.md, circle.yml, examples/chrome-for-testing/README.md, factory/.env, factory/CHANGELOG.md, factory/README.md, factory/docker-compose.yml, factory/factory.Dockerfile, factory/installScripts/chrome-for-testing/default.sh, factory/installScripts/chrome-for-testing/install-chrome-for-testing-version.js, factory/test-project/docker-compose.yml
- closes https://github.com/cypress-io/cypress-docker-images/issues/1367
Google targets web app testing with their [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) flavor of Chrome.
Currently the [cypress/factory](https://github.com/cypress-io/cypress-docker-images/tree/master/factory) build process supports the installation of [Google Chrome](https://www.google.com/chrome) by specifying [CHROME_VERSION](https://github.com/cypress-io/cypress-docker-images/tree/master/factory#chrome_version). It does not support Chrome for Testing.
Cypress introduced support for Chrome for Testing in [cypress@13.17.0](https://docs.cypress.io/app/references/changelog#13-17-0).
Google has restricted the use of the `--load-extension` flag in Chrome version 137 and above and …
=> feat: add Chrome for Testing to cypress/factory build process

factory/test-project/README.MD, factory/test-project/cypress/e2e/2-advanced-examples/actions.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/cypress_api.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/misc.cy.js, factory/test-project/cypress/e2e/2-advanced-examples/storage.cy.js
- [cypress@14.5.0](https://docs.cypress.io/app/references/changelog#14-5-0) updated to use [cypress-example-kitchensink@5.0.0](https://github.com/cypress-io/cypress-example-kitchensink/releases/tag/v5.0.0) in https://github.com/cypress-io/cypress/blob/develop/packages/example/package.json from previously [cypress-example-kitchensink@4.0.0](https://github.com/cypress-io/cypress-example-kitchensink/releases/tag/v4.0.0). This jump included some minor changes to the Cypress scaffolded example tests.
- The [factory/test-project](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/test-project) is manually built from the above source
- Re-scaffold the [factory/test-project](https://github.com/cypress-io/cypress-docker-images/tree/master/factory/test-project) according to the …
=> test: update test-project to cypress 14.5.0

factory/.env, factory/CHANGELOG.md
- Node.js released an update [Node.js v22.17.0 LTS](https://nodejs.org/en/blog/release/v22.17.0) on Jun 24, 2025.
| Environment variable           | Before             | After             |
| ------------------------------ | ------------------ | ----------------- |
| `FACTORY_VERSION`              | `5.11.0`           | `5.11.1`          |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.16.0`          | `22.17.0`         |
| `CHROME_VERSION`               | `137.0.7151.119-1` | `138.0.7204.49-1` |
| `EDGE_VERSION`                 | `137.0.3296.62-1`  | `137.0.3296.93-1` |
| `FIREFOX_VERSION`              | `139.0.4`          | `140.0`           |
=> fix(deps): update to Node.js 22.17.0

factory/.env, factory/CHANGELOG.md, factory/installScripts/node/default.sh
PR https://github.com/cypress-io/cypress-docker-images/pull/1377 implemented an emergency workaround to unblock building a Cypress Docker image based on Node.js 22.17.0 (Active LTS version) and signed with the key `C0D6248439F1D5604AAFFB4021D900FFDB233756`.
The original issue was that the keyserver hkps://keys.openpgp.org recognized the key `C0D6248439F1D5604AAFFB4021D900FFDB233756` and then skipped importing it. The user ID `duhamelantoine1995@gmail.com` had been moved to the newly created key `5BE8A3F6C8A5C01D106C0AD820B1A390B168D356` and was no longer available for the older key. This left the `cypress/factory` process unable to verify the Node.js 22.17.0 package and so the build failed. (https://github.com/cypress-io/cypress-docker-images/issues/1376 contains slightly more background …
=> fix: explicit check for Node.js key import

factory/.env, factory/CHANGELOG.md, factory/installScripts/node/default.sh
- closes https://github.com/cypress-io/cypress-docker-images/issues/1386
- responds to build and connectivity issues reported in https://github.com/cypress-io/cypress-docker-images/issues/1382
When importing [Node.js release keys](https://github.com/nodejs/node/blob/main/README.md#release-keys), if a key cannot be imported from the primary keyserver hkps://keys.openpgp.orgs and there is a network connection issue to the fallback keyserver `keyserver.ubuntu.com`, then importing **ALL** Node.js keys fails. This in turn causes a build failure, even if the corresponding key, that could not be imported, is not subsequently needed to verify the actual Node.js version selected with `NODE_VERSION`.
- `cypress/factory:5.11.3`
- `cypress/factory:5.11.4`
As a consequence of catastrophic verification …
=> fix: skip individual failed Node.js key imports

factory/.env, factory/CHANGELOG.md, factory/installScripts/node/default.sh
- Node.js released an update [Node.js v22.18.0 LTS](https://nodejs.org/en/blog/release/v22.18.0) on Jul 31, 2025.
| Environment variable           | Before             | After              |
| ------------------------------ | ------------------ | ------------------ |
| `FACTORY_VERSION`              | `5.12.0`           | `5.12.1`           |
| `FACTORY_DEFAULT_NODE_VERSION` | `22.17.1`          | `22.18.0`          |
| `CHROME_VERSION`               | `138.0.7204.157-1` | `138.0.7204.183-1` |
| `CHROME_FOR_TESTING_VERSION`   | `138.0.7204.157`   | `138.0.7204.183`   |
| `EDGE_VERSION`                 | `138.0.3351.83-1`  | `138.0.3351.121-1` |
| `FIREFOX_VERSION` …
=> fix(deps): update to Node.js 22.18.0

factory/test-project/cypress/e2e/2-advanced-examples/misc.cy.js
PR https://github.com/cypress-io/cypress/pull/32238 plans to update [execa](https://www.npmjs.com/package/execa) in Cypress from [execa@1.0.0](https://github.com/sindresorhus/execa/releases/tag/v1.0.0) to [execa@4.1.0](https://github.com/sindresorhus/execa/releases/tag/v4.1.0) and for [cy.exec()](https://docs.cypress.io/api/commands/exec#Yields) to yield property `exitCode` instead of `code`.
To adapt scaffold tests to work with both Cypress 14 and 15, PR https://github.com/cypress-io/cypress-example-kitchensink/pull/984 has been proposed, which would adapt the [cypress/e2e/2-advanced-examples/misc.cy.js](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress/e2e/2-advanced-examples/misc.cy.js) test spec accordingly.
These changes will be needed in the corresponding …
=> test: Cypress 15 test-project preparation

CONTRIBUTING.md, README.md, factory/.env, factory/CHANGELOG.md, factory/factory.Dockerfile
- Closes https://github.com/cypress-io/cypress-docker-images/issues/1387
Cypress Docker images built from [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) currently use `BASE_IMAGE='debian:12.11-slim'`. [Debian 13.0 (trixie)](https://www.debian.org/releases/trixie/), which was [released](https://www.debian.org/News/2025/20250809) on Aug 9, 2025, supersedes [Debian 12.x (bookworm)](https://www.debian.org/releases/bookworm/).
Corresponding Debian Docker images were made available on Aug 13, 2025.
Update the base image for `cypress/factory` to use [Debian 13.0 (trixie)](https://www.debian.org/releases/trixie/).
In detail, the environment variables in [factory/.env](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/.env) that …
=> feat: update BASE_IMAGE to debian:13.0-slim (trixie)

factory/.env
updates factory to Cypress 15 and updates browsers
=> chore: update to Cypress `15.0.0`

examples/basic/package-lock.json, examples/basic/package.json, examples/chrome-for-testing/package-lock.json, examples/chrome-for-testing/package.json, examples/chromium/package-lock.json, examples/chromium/package.json, examples/firefox-esr/package-lock.json, examples/firefox-esr/package.json
- Examples in the [examples](https://github.com/cypress-io/cypress-docker-images/tree/master/examples) sub-directories are currently configured to use [cypress@14.4.0](https://docs.cypress.io/app/references/changelog#14-4-0), released May 20, 2025.
- The latest version of Cypress is [cypress@15.0.0](https://docs.cypress.io/app/references/changelog#15-0-0), released Aug 20, 2025.
Update Cypress in [examples](https://github.com/cypress-io/cypress-docker-images/tree/master/examples) sub-directories to [cypress@15.0.0](https://docs.cypress.io/app/references/changelog#15-0-0) for parity with the latest released version of Cypress:
- [examples/basic](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/basic)
- [examples/chrome-for-testing](https://github.com/cypress-io/cypre …
=> test(deps): update Cypress in examples to 15.0.0

base-internal/releases/node-22/22.18.0-bullseye/Dockerfile, base-internal/releases/node-22/22.18.0-bullseye/README.md, base-internal/releases/node-22/22.18.0-bullseye/build.sh, base-internal/releases/node-22/22.18.0-glibc-2.31/Dockerfile, base-internal/releases/node-22/22.18.0-glibc-2.31/README.md, base-internal/releases/node-22/22.18.0-glibc-2.31/build.sh, base-internal/releases/node-22/22.18.0-yarn-berry/Dockerfile, base-internal/releases/node-22/22.18.0-yarn-berry/README.md, base-internal/releases/node-22/22.18.0-yarn-berry/build.sh, base-internal/releases/node-22/22.18.0/Dockerfile, base-internal/releases/node-22/22.18.0/README.md, base-internal/releases/node-22/22.18.0/build.sh
For https://github.com/cypress-io/cypress/pull/32371
Mostly following this pattern: https://github.com/cypress-io/cypress-docker-images/pull/1379/files
=> chore: publish base-internal with node 22.18.0

factory/.env, factory/CHANGELOG.md, factory/installScripts/edge/default.sh
- closes https://github.com/cypress-io/cypress-docker-images/issues/1404
- supersedes and closes https://github.com/cypress-io/cypress-docker-images/pull/1405
Installing Microsoft Edge through the `cypress/factory` process using the script [factory/installScripts/edge/default.sh](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/installScripts/edge/default.sh) causes two entries to be placed into `/etc/apt/sources.list.d`
- `microsoft-edge-stable.list`
The filename `/etc/apt/sources.list.d/microsoft-edge-stable.list` is explicitly generated by the Cypress Edge installation script [factory/installScripts/edge/default.sh](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/installScripts/edge/default.sh) and the installation process causes it to be …
=> fix: use microsoft-edge.list for Edge installation

README.md
- closes https://github.com/cypress-io/cypress-docker-images/issues/1393
In the table at the top of the [README](https://github.com/cypress-io/cypress-docker-images/blob/master/README.md) document, the column "Monthly pulls" is incorrectly labeled as "Monthly". It's the total since first publication:
---
The [Cypress organization on Docker Hub](https://hub.docker.com/u/cypress) shows the equivalent pull figures as the total number of pulls over all time, not a monthly figure.
---
Cypress Docker images are now in a mature phase of their life cycle and there is no sign that the presentation of download statistics has any influence on user's download choices.
Additionally, the picture is incomplete, since the statistics only refer to:
- [Docker Hub](https://hub.docker.com/u/cypress) and not …
=> docs: remove pull statistics from README

markdownLinkConfig.json
Executing `npm run check:markdown` results in errors checking the [./factory/README.md](https://github.com/cypress-io/cypress-docker-images/blob/master/factory/README.md) document:
```text
ERROR: 3 dead links found!
[✖] https://www.npmjs.com/package/yarn → Status: 403
[✖] https://www.npmjs.com/package/cypress → Status: 403
[✖] https://www.npmjs.com/package/geckodriver → Status: 403
```
These are [HTTP 403 Forbidden](https://developer.mozilla.org/de/docs/Web/HTTP/Reference/Status/403) errors, resulting from the npm registry refusing to honor non-browser requests.
- Add `^https://www.npmjs.com` to `ignorePatterns` in [markdownLinkConfig.json](https://github.com/cypress-io/cypress-docker-images/blob/master/markdownLinkConfig.json)
- Remove the existing `"pattern": "^#S*"`. This is not …
=> chore: exclude npm registry from link check

examples/basic/package-lock.json, examples/basic/package.json, examples/chrome-for-testing/package-lock.json, examples/chrome-for-testing/package.json, examples/chrome-for-testing/scripts/test.sh, examples/chromium/package-lock.json, examples/chromium/package.json, examples/firefox-esr/package-lock.json, examples/firefox-esr/package.json
- closes https://github.com/cypress-io/cypress-docker-images/issues/1417
- Examples in the [examples](https://github.com/cypress-io/cypress-docker-images/tree/master/examples) sub-directories, with exception of [examples/firefox-esr](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/firefox-esr), are currently configured to use [cypress@15.0.0](https://docs.cypress.io/app/references/changelog#15-0-0), released Aug 20, 2025.
- The [examples/firefox-esr](https://github.com/cypress-io/cypress-docker-images/tree/master/examples/firefox-esr) example directory was held back at [cypress@14.5.4](https://docs.cypress.io/app/references/changelog#14-5-4) pending release of a suitable Firefox ESR release as a Debian package. Debian `trixie` (`stable`) has now released …
=> test(deps): update Cypress in examples to 15.3.0
