internal/chrome/Dockerfile
internal/cy/Dockerfile

Set non-root user in internal images

---

base/8/Dockerfile

Update Node and NPM versions

---

base/10/Dockerfile

set base/10 from node:10.13

---

base/8/Dockerfile
base/README.md

Update Node 8 image to 8.12.
closes #65

Update to Latest Node 8 LTS

---

README.md
base/8.15.1/Dockerfile
base/8.15.1/README.md
base/8.15.1/build.sh
base/README.md

- closes #91 
- closes #89 
- closes #73 
Once merged, will build the image on Docker hub

Add Node 8.15.1 Docker image 

---

CONTRIBUTING.md
README.md
test/Dockerfile

add instructions, close #99

---

README.md
base/8.9.3/Dockerfile
base/8.9.3/README.md
base/8.9.3/build.sh
base/README.md
browsers/node8.9.3-chrome73/Dockerfile
browsers/node8.9.3-chrome73/README.md
browsers/node8.9.3-chrome73/build.sh
test/Dockerfile

We need it for Cypress 3.3.0 which will ship with Electron 2 and Node 8.9.3

Add image with Node 8.9.3

---

base/12.1.0/Dockerfile
base/12.1.0/README.md
base/12.1.0/build.sh
base/README.md

`cypress/base:12.1.0`
```
node version:    v12.1.0 
yarn version:    1.15.2 
debian version:  9.8 
```

feat: add cypress/base 12.1.0 image

---

README.md
base/README.md
browsers/README.md
included/3.2.0/README.md
included/README.md

Organize readme 107

---

.gitignore
base/12.4.0/Dockerfile
base/12.4.0/README.md
base/12.4.0/build.sh
base/README.md
browsers/README.md
browsers/node12.4.0-chrome76/Dockerfile
browsers/node12.4.0-chrome76/README.md
browsers/node12.4.0-chrome76/build.sh
test/Dockerfile

Add cypress/browsers:node12.4.0-chrome76, cypress/base:12.4.0

---

included/3.4.1/Dockerfile
included/3.4.1/README.md
included/3.4.1/build.sh
included/README.md
included/test.sh
test/Dockerfile

Add 1 new docker image with cypress 3.4.1

Add cypress/included:3.4.1

---

base/12.12.0/Dockerfile
base/12.12.0/README.md
base/12.12.0/build.sh
base/README.md
test/Dockerfile

Changes
Adds base/12.12.0 directory
Configures Dockerfile, README and build with proper node version
Updates test to pick up on 12.12.0 image

Add node 12.12.0 support for base

---

included/3.5.0/Dockerfile
included/3.5.0/README.md
included/3.5.0/build.sh
included/README.md

Add 1 new docker image with cypress 3.5.0.
```
node version:    v12.6.0 
npm version:     6.10.0 
yarn version:    1.16.0 
debian version:  9.9 
user:            root 
```

Add cypress/included:3.5.0

---

included/3.6.0/Dockerfile
included/3.6.0/README.md
included/3.6.0/build.sh
included/README.md

- closes #167
```
node version:    v12.6.0
npm version:     6.10.0
yarn version:    1.16.0
debian version:  9.9
```

Add image cypress/included:3.6.0

---

base/12.13.0/Dockerfile
base/12.13.0/README.md
base/12.13.0/build.sh
base/README.md
test/Dockerfile

Adds base/12.13.0 directory
Configures Dockerfile, README and build with proper node version
Updates test to pick up on 12.13.0 image

Add node 12.13.0 support for base

---

base/13.1.0/Dockerfile
base/13.1.0/README.md
base/13.1.0/build.sh
base/13.3.0/Dockerfile
base/13.3.0/README.md
base/13.3.0/build.sh
base/README.md
browsers/README.md
browsers/node13.1.0-chrome-78-ff70/Dockerfile
browsers/node13.1.0-chrome-78-ff70/README.md
browsers/node13.1.0-chrome-78-ff70/build.sh
browsers/node13.3.0-chrome-79-ff70/Dockerfile
browsers/node13.3.0-chrome-79-ff70/README.md
browsers/node13.3.0-chrome-79-ff70/build.sh
test/Dockerfile

Hi! My first PR here, please tell me if anything is wrong. I based it on the code for 12.13. All tests are passing — wasn't sure if I should keep the commit with test changes, so I let it be for now.

Add images for Node 13

---

.gitignore
README.md
examples/included-with-plugins/README.md
examples/included-with-plugins/src/.gitignore
examples/included-with-plugins/src/cypress.json
examples/included-with-plugins/src/cypress/integration/spec.js
examples/included-with-plugins/src/cypress/plugins/index.js
examples/included-with-plugins/src/cypress/support/index.js
examples/included-with-plugins/src/index.html
examples/included-with-plugins/src/package-lock.json
examples/included-with-plugins/src/package.json
examples/included-with-plugins/test.sh
examples/run-included-as-non-root/test.sh

Example with locally installed plugins running on top of cypress/included docker image

---

base/12.14.0/Dockerfile
base/12.14.0/README.md
base/12.14.0/build.sh

This PR adds a base image with Node `12.14.0`.

Add base image with Node 12.14.0

---

circle.yml
generate-config.js

Build browsers images on CI

---

circle.yml
generate-config.js
included/3.8.2/Dockerfile
included/3.8.2/README.md
included/3.8.2/build.sh

cypress/included:3.8.2

---

circle.yml
generate-config.js

- closes #223
Extra pre-caution

check if image exists again before pushing

---

browsers/node13.6.0-chrome-80-ff72/build.sh
circle.yml
generate-config.js

make sure we don't install a wrong Chrome when building browsers image

Check Chrome version

---

circle.yml
generate-config.js

- closes #229 
This is the situation that used to trip us and cause a Docker image build and upload

using docker-image-not-found to check if image exists

---

browsers/README.md

update browsers latest tag text

---

generate-base-image.js

print node libs versions in base image

---

browsers/node12.13.0-chrome80-ff73/Dockerfile
browsers/node12.13.0-chrome80-ff73/README.md
browsers/node12.13.0-chrome80-ff73/build.sh
circle.yml

For https://github.com/cypress-io/cypress/pull/6318

Add node12.13.0-chrome80-ff73

---

base/8.0.0/Dockerfile
base/README.md

- forcing NPM v6 inside Node 8.0.0 image by installing it locally and then creating a global link to it

Install npm 6

---

circle.yml
generate-config.js

test Chrome and Firefox

---

generate-base-image.js

add missing libgbm-dev pupetteer dependency

---

browsers/README.md
browsers/check-chrome-versions.sh
browsers/node12.18.0-chrome83-ff77/Dockerfile
browsers/node12.18.0-chrome83-ff77/README.md
browsers/node12.18.0-chrome83-ff77/build.sh
circle.yml

Add node 12.18.0, Chrome 83 / Firefox 77 browsers image

Add node 12.18.0, Chrome 83 / Firefox 77 browsers image

---

browsers/README.md
browsers/node14.0.0-chrome84/Dockerfile
browsers/node14.0.0-chrome84/README.md
browsers/node14.0.0-chrome84/build.sh
circle.yml

```
node version:    v14.7.0
npm version:     6.14.4
yarn version:    1.22.4
debian version:  10.3
Chrome version:  Google Chrome 84.0.4147.105
git version:     git version 2.20.1
```

add browser image with node 14.7 and chrome 84

---

README.md
base/README.md
browsers/README.md
included/README.md

Reading the readmes, I thought `included` did not include any browsers because it wasn’t mentioned. 
- Updated to mention that included includes some browsers
- Made the language consistent across readmes
- Minor other edits to readmes

Update readmes to more clearly define what's included in each image section

---

browsers/README.md
browsers/node12.14.1-chrome85-ff81/Dockerfile
browsers/node12.14.1-chrome85-ff81/README.md
browsers/node12.14.1-chrome85-ff81/build.sh
circle.yml

add browsers-node12.14.1-chrome85-ff81

add browsers-node12.14.1-chrome85-ff81 

---

browsers/node12.18.3-chrome83-ff77/Dockerfile
browsers/node12.18.3-chrome83-ff77/README.md
browsers/node12.18.3-chrome83-ff77/build.sh
circle.yml

Added browser image using node 12.18.3

Add cypress/browsers:node12.18.3-chrome83-ff77 image

---

base/README.md
base/manjaro-14.12.0/Dockerfile
base/manjaro-14.12.0/README.md
base/manjaro-14.12.0/build.sh
circle.yml
generate-config.js

- closes #378
note that our base images do NOT include browsers and do NOT include Cypress itself, only OS dependencies
```
node:    v14.12.0
npm:     6.14.8
yarn:    1.22.10
user:    root
git:     git version 2.28.0
```

Add Manjaro Docker image

---

browsers/README.md
browsers/node14.15.0-chrome86-ff82/Dockerfile
browsers/node14.15.0-chrome86-ff82/README.md
browsers/node14.15.0-chrome86-ff82/build.sh
circle.yml

I copied `cypress/browsers:node12.14.1-chrome85-ff81` and changed the node version number

feat: add browser image based on node 14.15.0

---

generate-base-image.js

base: add vim and nano to the Docker image

---

generate-base-image.js

Already implemented as a concept in #429; since asked for a file change it's now in the image generation script. I assume that means the implementation of #425 is accepted in general and just has to be in the right place.

reimplemented cache cleaning (#429) for new images

---

package-lock.json
package.json
scripts/create-commit.sh
scripts/generate-base-image.js
scripts/generate-browser-image.js
scripts/generate-commit.js
scripts/generate-included-image.js
utils.js
yarn.lock

This PR automates the process of commiting changes made as a result of running a `generation` script. It works as follows:
1. A user runs one of the generation script like: `yarn add:base -- 13.6.0`
2. The script then creates a new base image
3. The script updates the CHANGELOG for `/base`
4. The script asks the user if they want to commit their changes
- If user types `y` or `yes` this script runs which creates a commit with appropriate message
- If user types `n` or `no` the script will skip this step and finish.

Dx 804 create script to create new commit with new image details

---

scripts/generate-browser-image.js

This avoids a lot of log spam during docker build, e.g.
https://app.circleci.com/pipelines/github/cypress-io/cypress-docker-images/706/workflows/12e738d9-dbbe-43c1-b493-eb22af187583/jobs/36273?invite=true#step-103-371

reduce logspam using same pattern as in FF download

---

scripts/generate-base-image.js
scripts/generate-browser-image.js

fix: update ENV vars. add curl dependency.

---

scripts/generate-base-image.js

fix: add missing ps package.

---

scripts/generate-included-image.js

fix: remove extra step that caused browsers to update in included images

---

base/CHANGELOG.md
markdownLinkConfig.json
package.json
yarn.lock

I've been noticing failures related to this package (like #704). I updated and it seemed to fix the issues, but did reveal a legitimate failure - that I fixed.

fix: update markdown-link-checker package. fix broken link.

---

CONTRIBUTING.md
scripts/generate-included-image.js

This PR adds global Typescript support to the included images script
Closes #567

feat(scripts): add global typescript support

---

scripts/includes/circle-header.yml

Change `--password-stdin` to `--password $(aws ecr-public get-login-pw)` in order to avoid TTY.

fix: update ECR password var

---

circle.yml
factory/.env

PR to update browser versions to latest.

Update browser versions

---

README.md

Expanding best practices to include note about image security.

Add security best practice note

---

factory/.env
factory/test-project/docker-compose.yml

update chrome and edge versions

chore: update chrome and edge versions

---

factory/.env
factory/CHANGELOG.md
factory/factory.Dockerfile

Remove critical vulnerabilities identified in curl/libcurl.
See #852

security: remove critical vulnerabilities

---

browsers-internal/node18.15.0-chrome114-ff115-edge/Dockerfile
browsers-internal/node18.15.0-chrome114-ff115-edge/README.md
browsers-internal/node18.15.0-chrome114-ff115-edge/build.sh
browsers-internal/node18.15.0-chrome114-ff115-edge/global-profile.sh

needed for origin tests against auth providers that test against `microsoft-edge` and need `curl` installed

chore: add internal image with edge to test in origin providers

---

base-internal/ubuntu20-node18/Dockerfile
base-internal/ubuntu20-node18/README.md
base-internal/ubuntu20-node18/build.sh
base-internal/ubuntu22-node18/Dockerfile
base-internal/ubuntu22-node18/README.md
base-internal/ubuntu22-node18/build.sh

Adds Ubuntu 20 & 22 images for Node 18. used in https://github.com/cypress-io/cypress/pull/27941

chore: add Ubuntu 20/22 images for node 18

---

factory/.env

PR to create an image for the `13.5.0` release

chore: release 13.5.0 image

---

factory/.env

chore: image for release 13.5.1

---

factory/.env

chore: release for 13.6.0

---

factory/.env

Builds images for `13.6.2` release

chore: build images for 13.6.2 release

---

base-internal/18.18.2/Dockerfile
base-internal/18.18.2/README.md
base-internal/18.18.2/build.sh
browsers-internal/node18.18.2-chrome120-ff115-edge/Dockerfile
browsers-internal/node18.18.2-chrome120-ff115-edge/README.md
browsers-internal/node18.18.2-chrome120-ff115-edge/build.sh
browsers-internal/node18.18.2-chrome120-ff115-edge/global-profile.sh
browsers-internal/node18.18.2-chrome120-ff115/Dockerfile
browsers-internal/node18.18.2-chrome120-ff115/README.md
browsers-internal/node18.18.2-chrome120-ff115/build.sh
browsers-internal/node18.18.2-chrome120-ff115/global-profile.sh

Prerequisite images for https://github.com/cypress-io/cypress/pull/28959

Publish browsers-internal and base-internal for Electron 28

---

factory/.env

updates factory with cypress `13.6.6`

bump cypress version in factory

---

factory/.env

Updates cypress to 13.8.0 and updates browser images to latest

update to cypress 13.8.0 and update browser images

---

factory/.env

also updates chrome to latest stable

chore: update factory to use cypress 13.14.1

---

base-internal/releases/node-20/20.18.0-yarn-berry/Dockerfile
base-internal/releases/node-20/20.18.0-yarn-berry/README.md
base-internal/releases/node-20/20.18.0-yarn-berry/build.sh

Add 20.18.0 yarn berry image for testing yarn-pnp-preprocessor-system-test

chore: add 20.18.0 yarn berry image for testing yarn-pnp-preprocessor-system-test

---

factory/.env

updates browsers and cypress to latest

chore: update browsers and cypress to latest (14.1.0)

---

factory/CHANGELOG.md

docs: fix changelog typos

---

factory/.env

Updates the factory to Cypress 15.1.0

chore: update factory to use Cypress 15.1.0

---

factory/.env

updates cypress and browsers to latest

chore: update cypress to 15.2.0

---

base-internal/releases/node-22/22.19.0-bullseye/Dockerfile
base-internal/releases/node-22/22.19.0-bullseye/README.md
base-internal/releases/node-22/22.19.0-bullseye/build.sh
base-internal/releases/node-22/22.19.0-glibc-2.31/Dockerfile
base-internal/releases/node-22/22.19.0-glibc-2.31/README.md
base-internal/releases/node-22/22.19.0-glibc-2.31/build.sh
base-internal/releases/node-22/22.19.0-yarn-berry/Dockerfile
base-internal/releases/node-22/22.19.0-yarn-berry/README.md
base-internal/releases/node-22/22.19.0-yarn-berry/build.sh
base-internal/releases/node-22/22.19.0/Dockerfile
base-internal/releases/node-22/22.19.0/README.md
base-internal/releases/node-22/22.19.0/build.sh

For https://github.com/cypress-io/cypress/pull/32607

chore: Publish base-internal with node 22.19.0
